
// Generated by Cadence Genus Synthesis Solution 15.10-s019_1

// Verification Directory fv/proccessor 

module mux(out, select, input1, input2);
  input select;
  input [7:0] input1, input2;
  output [7:0] out;
  wire select;
  wire [7:0] input1, input2;
  wire [7:0] out;
  CLKMX2X12 g134(.A (input2[1]), .B (input1[1]), .S0 (select), .Y
       (out[1]));
  CLKMX2X12 g135(.A (input2[4]), .B (input1[4]), .S0 (select), .Y
       (out[4]));
  CLKMX2X12 g136(.A (input2[7]), .B (input1[7]), .S0 (select), .Y
       (out[7]));
  CLKMX2X12 g137(.A (input2[0]), .B (input1[0]), .S0 (select), .Y
       (out[0]));
  CLKMX2X12 g138(.A (input2[5]), .B (input1[5]), .S0 (select), .Y
       (out[5]));
  CLKMX2X12 g139(.A (input2[6]), .B (input1[6]), .S0 (select), .Y
       (out[6]));
  CLKMX2X12 g140(.A (input2[3]), .B (input1[3]), .S0 (select), .Y
       (out[3]));
  CLKMX2X12 g141(.A (input2[2]), .B (input1[2]), .S0 (select), .Y
       (out[2]));
endmodule

module mux_29(out, select, input1, input2);
  input select;
  input [7:0] input1, input2;
  output [7:0] out;
  wire select;
  wire [7:0] input1, input2;
  wire [7:0] out;
  CLKMX2X12 g134(.A (input2[1]), .B (input1[1]), .S0 (select), .Y
       (out[1]));
  CLKMX2X12 g135(.A (input2[4]), .B (input1[4]), .S0 (select), .Y
       (out[4]));
  CLKMX2X12 g136(.A (input2[7]), .B (input1[7]), .S0 (select), .Y
       (out[7]));
  CLKMX2X12 g137(.A (input2[0]), .B (input1[0]), .S0 (select), .Y
       (out[0]));
  CLKMX2X12 g138(.A (input2[5]), .B (input1[5]), .S0 (select), .Y
       (out[5]));
  CLKMX2X12 g139(.A (input2[6]), .B (input1[6]), .S0 (select), .Y
       (out[6]));
  CLKMX2X12 g140(.A (input2[3]), .B (input1[3]), .S0 (select), .Y
       (out[3]));
  CLKMX2X12 g141(.A (input2[2]), .B (input1[2]), .S0 (select), .Y
       (out[2]));
endmodule

module alu(out, Data1, Data2, Select);
  input [7:0] Data1, Data2;
  input [2:0] Select;
  output [7:0] out;
  wire [7:0] Data1, Data2;
  wire [2:0] Select;
  wire [7:0] out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77;
  TLATNXL \out_reg[0] (.GN (Select[2]), .D (n_46), .Q (UNCONNECTED),
       .QN (n_50));
  TLATNXL \out_reg[1] (.GN (Select[2]), .D (n_51), .Q (UNCONNECTED0),
       .QN (n_55));
  TLATNXL \out_reg[2] (.GN (Select[2]), .D (n_56), .Q (UNCONNECTED1),
       .QN (n_60));
  TLATNXL \out_reg[3] (.GN (Select[2]), .D (n_61), .Q (UNCONNECTED2),
       .QN (n_65));
  TLATNXL \out_reg[4] (.GN (Select[2]), .D (n_66), .Q (UNCONNECTED3),
       .QN (n_69));
  TLATNXL \out_reg[5] (.GN (Select[2]), .D (n_70), .Q (UNCONNECTED4),
       .QN (n_72));
  TLATNXL \out_reg[6] (.GN (Select[2]), .D (n_73), .Q (UNCONNECTED5),
       .QN (n_75));
  TLATNXL \out_reg[7] (.GN (Select[2]), .D (n_76), .Q (UNCONNECTED6),
       .QN (n_77));
  INVX12 g805(.A (n_77), .Y (out[7]));
  OAI2BB1X1 g806(.A0N (n_27), .A1N (Data1[7]), .B0 (n_74), .Y (n_76));
  INVX12 g808(.A (n_75), .Y (out[6]));
  AOI22XL g809(.A0 (n_2), .A1 (n_71), .B0 (Data2[7]), .B1 (n_25), .Y
       (n_74));
  OAI221X1 g810(.A0 (n_3), .A1 (n_68), .B0 (n_11), .B1 (n_15), .C0
       (n_37), .Y (n_73));
  INVX12 g812(.A (n_72), .Y (out[5]));
  XNOR2X1 g813(.A (n_21), .B (n_67), .Y (n_71));
  OAI221X1 g814(.A0 (n_3), .A1 (n_62), .B0 (n_11), .B1 (n_14), .C0
       (n_39), .Y (n_70));
  INVX12 g816(.A (n_69), .Y (out[4]));
  CLKXOR2X1 g817(.A (n_63), .B (n_19), .Y (n_68));
  OAI21XL g818(.A0 (n_15), .A1 (n_64), .B0 (n_17), .Y (n_67));
  OAI221X1 g819(.A0 (n_3), .A1 (n_57), .B0 (n_11), .B1 (n_13), .C0
       (n_40), .Y (n_66));
  INVX12 g821(.A (n_65), .Y (out[3]));
  INVX1 g822(.A (n_63), .Y (n_64));
  CLKXOR2X1 g823(.A (n_58), .B (n_24), .Y (n_62));
  OAI21XL g824(.A0 (n_14), .A1 (n_59), .B0 (n_9), .Y (n_63));
  OAI221X1 g825(.A0 (n_3), .A1 (n_52), .B0 (n_11), .B1 (n_12), .C0
       (n_36), .Y (n_61));
  INVX12 g827(.A (n_60), .Y (out[2]));
  INVX1 g828(.A (n_58), .Y (n_59));
  CLKXOR2X1 g829(.A (n_53), .B (n_28), .Y (n_57));
  OAI21XL g830(.A0 (n_13), .A1 (n_54), .B0 (n_10), .Y (n_58));
  OAI221X1 g831(.A0 (n_3), .A1 (n_47), .B0 (n_11), .B1 (n_16), .C0
       (n_38), .Y (n_56));
  INVX12 g833(.A (n_55), .Y (out[1]));
  INVX1 g834(.A (n_53), .Y (n_54));
  CLKXOR2X1 g835(.A (n_48), .B (n_22), .Y (n_52));
  OAI21XL g836(.A0 (n_12), .A1 (n_49), .B0 (n_7), .Y (n_53));
  OAI221X1 g837(.A0 (n_3), .A1 (n_42), .B0 (n_11), .B1 (n_8), .C0
       (n_41), .Y (n_51));
  INVX12 g839(.A (n_50), .Y (out[0]));
  INVX1 g840(.A (n_48), .Y (n_49));
  CLKXOR2X1 g841(.A (n_44), .B (n_20), .Y (n_47));
  OAI21XL g842(.A0 (n_45), .A1 (n_16), .B0 (n_18), .Y (n_48));
  OAI211XL g843(.A0 (n_0), .A1 (n_5), .B0 (n_29), .C0 (n_43), .Y
       (n_46));
  INVX1 g844(.A (n_44), .Y (n_45));
  OAI21XL g845(.A0 (n_5), .A1 (n_8), .B0 (n_6), .Y (n_44));
  AOI22XL g846(.A0 (n_2), .A1 (n_26), .B0 (n_27), .B1 (Data1[0]), .Y
       (n_43));
  XNOR2X1 g847(.A (n_5), .B (n_23), .Y (n_42));
  AOI21XL g848(.A0 (n_4), .A1 (Data1[1]), .B0 (n_32), .Y (n_41));
  AOI21XL g849(.A0 (n_4), .A1 (Data1[4]), .B0 (n_33), .Y (n_40));
  AOI21XL g850(.A0 (n_4), .A1 (Data1[5]), .B0 (n_30), .Y (n_39));
  AOI21XL g851(.A0 (n_4), .A1 (Data1[2]), .B0 (n_31), .Y (n_38));
  AOI21XL g852(.A0 (n_4), .A1 (Data1[6]), .B0 (n_35), .Y (n_37));
  AOI21XL g853(.A0 (n_4), .A1 (Data1[3]), .B0 (n_34), .Y (n_36));
  NOR2XL g854(.A (Select[0]), .B (n_17), .Y (n_35));
  NOR2XL g855(.A (n_0), .B (n_7), .Y (n_34));
  NOR2XL g856(.A (Select[0]), .B (n_10), .Y (n_33));
  NOR2XL g857(.A (Select[0]), .B (n_6), .Y (n_32));
  NOR2XL g858(.A (Select[0]), .B (n_18), .Y (n_31));
  NOR2XL g859(.A (Select[0]), .B (n_9), .Y (n_30));
  NAND2BX1 g860(.AN (n_11), .B (Data2[0]), .Y (n_29));
  NAND2BX1 g861(.AN (n_13), .B (n_10), .Y (n_28));
  CLKXOR2X1 g862(.A (Data2[0]), .B (Data1[0]), .Y (n_26));
  OAI2BB1X1 g863(.A0N (n_1), .A1N (Data1[7]), .B0 (n_11), .Y (n_25));
  NAND2BX1 g864(.AN (n_14), .B (n_9), .Y (n_24));
  NAND2BX1 g865(.AN (n_8), .B (n_6), .Y (n_23));
  NAND2BX1 g866(.AN (n_4), .B (n_11), .Y (n_27));
  NAND2BX1 g867(.AN (n_12), .B (n_7), .Y (n_22));
  XNOR2X1 g868(.A (Data2[7]), .B (Data1[7]), .Y (n_21));
  NAND2BX1 g869(.AN (n_16), .B (n_18), .Y (n_20));
  NAND2BX1 g870(.AN (n_15), .B (n_17), .Y (n_19));
  NAND2X1 g871(.A (Data2[2]), .B (Data1[2]), .Y (n_18));
  NAND2X1 g872(.A (Data2[6]), .B (Data1[6]), .Y (n_17));
  NOR2XL g873(.A (Data2[2]), .B (Data1[2]), .Y (n_16));
  NOR2XL g874(.A (Data2[6]), .B (Data1[6]), .Y (n_15));
  NOR2XL g875(.A (Data2[5]), .B (Data1[5]), .Y (n_14));
  NOR2XL g876(.A (Data2[4]), .B (Data1[4]), .Y (n_13));
  NOR2XL g877(.A (Data2[3]), .B (Data1[3]), .Y (n_12));
  NAND2X2 g878(.A (Select[1]), .B (Select[0]), .Y (n_11));
  INVX1 g879(.A (n_3), .Y (n_2));
  NAND2X1 g880(.A (Data2[4]), .B (Data1[4]), .Y (n_10));
  NAND2X1 g881(.A (Data2[5]), .B (Data1[5]), .Y (n_9));
  NOR2XL g882(.A (Data2[1]), .B (Data1[1]), .Y (n_8));
  NAND2X1 g883(.A (Data2[3]), .B (Data1[3]), .Y (n_7));
  NAND2X1 g884(.A (Data2[1]), .B (Data1[1]), .Y (n_6));
  NAND2X1 g885(.A (Data2[0]), .B (Data1[0]), .Y (n_5));
  NOR2X1 g886(.A (Select[1]), .B (Select[0]), .Y (n_4));
  NAND2BX1 g887(.AN (Select[1]), .B (Select[0]), .Y (n_3));
  INVX1 g888(.A (Select[0]), .Y (n_1));
  BUFX2 drc_bufs894(.A (Select[0]), .Y (n_0));
endmodule

module compliment(out, in);
  input [7:0] in;
  output [7:0] out;
  wire [7:0] in;
  wire [7:0] out;
  wire [7:0] comp;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_23, n_24, n_25, n_27;
  wire n_28, n_30, n_31, n_33, n_34, n_35;
  CLKMX2X12 g627(.A (n_34), .B (n_35), .S0 (n_16), .Y (out[7]));
  INVX12 g628(.A (n_33), .Y (out[6]));
  INVX1 g629(.A (n_34), .Y (n_35));
  ADDFXL g630(.A (n_6), .B (n_11), .CI (n_30), .CO (n_34), .S (n_33));
  INVX12 g631(.A (n_31), .Y (out[5]));
  ADDFXL g632(.A (n_2), .B (n_9), .CI (n_27), .CO (n_30), .S (n_31));
  INVX12 g633(.A (n_28), .Y (out[4]));
  ADDFXL g634(.A (n_5), .B (n_7), .CI (n_24), .CO (n_27), .S (n_28));
  INVX12 g635(.A (n_25), .Y (out[3]));
  ADDFXL g636(.A (n_4), .B (n_8), .CI (n_23), .CO (n_24), .S (n_25));
  OA21X1 g637(.A0 (n_14), .A1 (n_20), .B0 (n_15), .Y (n_23));
  CLKMX2X12 g638(.A (n_20), .B (n_19), .S0 (n_17), .Y (out[2]));
  INVX12 g639(.A (n_18), .Y (out[1]));
  INVX1 g640(.A (n_20), .Y (n_19));
  ADDFXL g641(.A (comp[1]), .B (in[1]), .CI (n_1), .CO (n_20), .S
       (n_18));
  NAND2BX1 g642(.AN (n_14), .B (n_15), .Y (n_17));
  XNOR2X1 g643(.A (n_3), .B (n_12), .Y (n_16));
  NAND2X1 g644(.A (comp[1]), .B (n_10), .Y (n_15));
  NOR2XL g645(.A (comp[1]), .B (n_10), .Y (n_14));
  CLKMX2X12 g646(.A (n_0), .B (in[0]), .S0 (comp[0]), .Y (out[0]));
  CLKXOR2X1 g647(.A (comp[7]), .B (in[7]), .Y (n_12));
  CLKXOR2X1 g648(.A (comp[6]), .B (in[6]), .Y (n_11));
  CLKXOR2X1 g649(.A (comp[5]), .B (in[5]), .Y (n_9));
  CLKXOR2X1 g650(.A (comp[3]), .B (in[3]), .Y (n_8));
  CLKXOR2X1 g651(.A (comp[4]), .B (in[4]), .Y (n_7));
  XNOR2X1 g652(.A (comp[2]), .B (in[2]), .Y (n_10));
  NAND2BX1 g653(.AN (in[5]), .B (comp[5]), .Y (n_6));
  NAND2BX1 g654(.AN (in[3]), .B (comp[3]), .Y (n_5));
  NAND2BX1 g655(.AN (in[2]), .B (comp[2]), .Y (n_4));
  NAND2BX1 g656(.AN (in[6]), .B (comp[6]), .Y (n_3));
  NAND2BX1 g657(.AN (in[4]), .B (comp[4]), .Y (n_2));
  NAND2X1 g658(.A (comp[0]), .B (n_0), .Y (n_1));
  INVX1 g659(.A (in[0]), .Y (n_0));
endmodule

module counter(Read_addr, clk, reset);
  input clk, reset;
  output [2:0] Read_addr;
  wire clk, reset;
  wire [2:0] Read_addr;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, n_1, n_2, n_3, n_4,
       n_5;
  wire n_6;
  DFFNSRX2 \Read_addr_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_6), .Q (Read_addr[2]), .QN (UNCONNECTED7));
  NOR2XL g46(.A (reset), .B (n_5), .Y (n_6));
  DFFNSRX2 \Read_addr_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_4), .Q (Read_addr[1]), .QN (UNCONNECTED8));
  XNOR2X1 g48(.A (Read_addr[2]), .B (n_2), .Y (n_5));
  NOR2BX1 g49(.AN (n_3), .B (reset), .Y (n_4));
  ADDHXL g50(.A (Read_addr[0]), .B (Read_addr[1]), .CO (n_2), .S (n_3));
  DFFNSRX2 \Read_addr_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_1), .Q (Read_addr[0]), .QN (UNCONNECTED9));
  NOR2XL g52(.A (reset), .B (Read_addr[0]), .Y (n_1));
endmodule

module CU(OUT1addr, OUT2addr, INaddr, immediate, Select, imm_signal,
     comp_signal, instruction);
  input [31:0] instruction;
  output [2:0] OUT1addr, OUT2addr, INaddr, Select;
  output [7:0] immediate;
  output imm_signal, comp_signal;
  wire [31:0] instruction;
  wire [2:0] OUT1addr, OUT2addr, INaddr, Select;
  wire [7:0] immediate;
  wire imm_signal, comp_signal;
  wire n_0, n_1, n_3, n_4;
  AND2X1 g51(.A (instruction[24]), .B (n_1), .Y (comp_signal));
  NOR2BX2 g52(.AN (n_1), .B (instruction[24]), .Y (imm_signal));
  NAND3BXL g54(.AN (instruction[26]), .B (instruction[27]), .C (n_3),
       .Y (n_4));
  NOR2XL g55(.A (instruction[28]), .B (instruction[29]), .Y (n_3));
  INVX1 drc_bufs(.A (n_0), .Y (n_1));
  OR4X1 g2(.A (instruction[31]), .B (instruction[30]), .C
       (instruction[25]), .D (n_4), .Y (n_0));
endmodule

module regInstructions(instruction, clk, Read_Addr);
  input clk;
  input [2:0] Read_Addr;
  output [31:0] instruction;
  wire clk;
  wire [2:0] Read_Addr;
  wire [31:0] instruction;
  wire UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13,
       UNCONNECTED14, UNCONNECTED15, UNCONNECTED16, UNCONNECTED17;
  wire UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25;
  wire UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, UNCONNECTED29,
       UNCONNECTED30, UNCONNECTED31, \addr1[0]_444 , \addr1[1]_435 ;
  wire \addr1[2]_426 , \addr1[3]_408 , \addr1[4]_399 , \addr1[5]_390 ,
       \addr1[6]_381 , \addr1[7]_372 , \addr1[8]_363 , \addr1[9]_354 ;
  wire \addr1[10]_345 , \addr1[16]_327 , \addr1[17]_318 ,
       \addr1[18]_309 , \addr1[24]_489 , \addr1[25]_480 ,
       \addr1[26]_471 , \addr1[27]_462 ;
  wire \addr1[28]_453 , \addr1[29]_417 , \addr1[30]_336 ,
       \addr1[31]_293 , \addr2[0]_445 , \addr2[1]_436 , \addr2[2]_427 ,
       \addr2[3]_409 ;
  wire \addr2[4]_400 , \addr2[5]_391 , \addr2[6]_382 , \addr2[7]_373 ,
       \addr2[8]_364 , \addr2[9]_355 , \addr2[10]_346 , \addr2[16]_328 ;
  wire \addr2[17]_319 , \addr2[18]_310 , \addr2[24]_490 ,
       \addr2[25]_481 , \addr2[26]_472 , \addr2[27]_463 ,
       \addr2[28]_454 , \addr2[29]_418 ;
  wire \addr2[30]_337 , \addr2[31]_295 , \addr3[0]_446 , \addr3[1]_437
       , \addr3[2]_428 , \addr3[3]_410 , \addr3[4]_401 , \addr3[5]_392 ;
  wire \addr3[6]_383 , \addr3[7]_374 , \addr3[8]_365 , \addr3[9]_356 ,
       \addr3[10]_347 , \addr3[16]_329 , \addr3[17]_320 ,
       \addr3[18]_311 ;
  wire \addr3[24]_491 , \addr3[25]_482 , \addr3[26]_473 ,
       \addr3[27]_464 , \addr3[28]_455 , \addr3[29]_419 ,
       \addr3[30]_338 , \addr3[31]_297 ;
  wire \addr4[0]_447 , \addr4[1]_438 , \addr4[2]_429 , \addr4[3]_411 ,
       \addr4[4]_402 , \addr4[5]_393 , \addr4[6]_384 , \addr4[7]_375 ;
  wire \addr4[8]_366 , \addr4[9]_357 , \addr4[10]_348 , \addr4[16]_330
       , \addr4[17]_321 , \addr4[18]_312 , \addr4[24]_492 ,
       \addr4[25]_483 ;
  wire \addr4[26]_474 , \addr4[27]_465 , \addr4[28]_456 ,
       \addr4[29]_420 , \addr4[30]_339 , \addr4[31]_299 , \addr5[0]_448
       , \addr5[1]_439 ;
  wire \addr5[2]_430 , \addr5[3]_412 , \addr5[4]_403 , \addr5[5]_394 ,
       \addr5[6]_385 , \addr5[7]_376 , \addr5[8]_367 , \addr5[9]_358 ;
  wire \addr5[10]_349 , \addr5[16]_331 , \addr5[17]_322 ,
       \addr5[18]_313 , \addr5[24]_493 , \addr5[25]_484 ,
       \addr5[26]_475 , \addr5[27]_466 ;
  wire \addr5[28]_457 , \addr5[29]_421 , \addr5[30]_340 ,
       \addr5[31]_301 , \addr6[0]_449 , \addr6[1]_440 , \addr6[2]_431 ,
       \addr6[3]_413 ;
  wire \addr6[4]_404 , \addr6[5]_395 , \addr6[6]_386 , \addr6[7]_377 ,
       \addr6[8]_368 , \addr6[9]_359 , \addr6[10]_350 , \addr6[16]_332 ;
  wire \addr6[17]_323 , \addr6[18]_314 , \addr6[24]_494 ,
       \addr6[25]_485 , \addr6[26]_476 , \addr6[27]_467 ,
       \addr6[28]_458 , \addr6[29]_422 ;
  wire \addr6[30]_341 , \addr6[31]_303 , \addr7[0]_450 , \addr7[1]_441
       , \addr7[2]_432 , \addr7[3]_414 , \addr7[4]_405 , \addr7[5]_396 ;
  wire \addr7[6]_387 , \addr7[7]_378 , \addr7[8]_369 , \addr7[9]_360 ,
       \addr7[10]_351 , \addr7[16]_333 , \addr7[17]_324 ,
       \addr7[18]_315 ;
  wire \addr7[24]_495 , \addr7[25]_486 , \addr7[26]_477 ,
       \addr7[27]_468 , \addr7[28]_459 , \addr7[29]_423 ,
       \addr7[30]_342 , \addr7[31]_305 ;
  wire \addr8[0]_451 , \addr8[1]_442 , \addr8[2]_433 , \addr8[3]_415 ,
       \addr8[4]_406 , \addr8[5]_397 , \addr8[6]_388 , \addr8[7]_379 ;
  wire \addr8[8]_370 , \addr8[9]_361 , \addr8[10]_352 , \addr8[16]_334
       , \addr8[17]_325 , \addr8[18]_316 , \addr8[24]_496 ,
       \addr8[25]_487 ;
  wire \addr8[26]_478 , \addr8[27]_469 , \addr8[28]_460 ,
       \addr8[29]_424 , \addr8[30]_343 , \addr8[31]_307 , n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_20, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_135, n_139, n_140, n_142, n_143, n_145, n_147;
  wire n_148, n_153, n_154, n_155, n_156, n_160, n_161, n_165;
  wire n_168, n_172, n_176, n_187, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_234, n_235;
  wire n_236, n_237, n_238, n_239, n_240, n_241, n_242, n_243;
  wire n_244, n_245, n_246, n_247, n_248, n_249, n_250, n_251;
  wire n_252;
  DFFNSRXL \instruction_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_247), .Q (UNCONNECTED10), .QN (n_193));
  DFFNSRXL \instruction_reg[10] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_251), .Q (instruction[10]), .QN (UNCONNECTED11));
  DFFNSRX1 \instruction_reg[16] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_240), .Q (instruction[16]), .QN (UNCONNECTED12));
  DFFNSRX1 \instruction_reg[17] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_176), .Q (instruction[17]), .QN (UNCONNECTED13));
  DFFNSRX1 \instruction_reg[18] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_235), .Q (instruction[18]), .QN (UNCONNECTED14));
  DFFNSRXL \instruction_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_237), .Q (UNCONNECTED15), .QN (n_194));
  DFFNSRXL \instruction_reg[24] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_241), .Q (UNCONNECTED16), .QN (n_199));
  DFFNSRXL \instruction_reg[25] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_248), .Q (UNCONNECTED17), .QN (n_191));
  DFFNSRXL \instruction_reg[26] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_244), .Q (instruction[26]), .QN (UNCONNECTED18));
  DFFNSRXL \instruction_reg[27] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_250), .Q (instruction[27]), .QN (UNCONNECTED19));
  DFFNSRXL \instruction_reg[28] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_236), .Q (instruction[28]), .QN (UNCONNECTED20));
  DFFNSRXL \instruction_reg[29] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_187), .Q (instruction[29]), .QN (UNCONNECTED21));
  DFFNSRXL \instruction_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_234), .Q (UNCONNECTED22), .QN (n_192));
  DFFNSRXL \instruction_reg[30] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_239), .Q (instruction[30]), .QN (UNCONNECTED23));
  DFFNSRXL \instruction_reg[31] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_242), .Q (instruction[31]), .QN (UNCONNECTED24));
  DFFNSRXL \instruction_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_243), .Q (UNCONNECTED25), .QN (n_195));
  DFFNSRXL \instruction_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_245), .Q (UNCONNECTED26), .QN (n_196));
  DFFNSRXL \instruction_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_246), .Q (UNCONNECTED27), .QN (n_197));
  DFFNSRXL \instruction_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_249), .Q (UNCONNECTED28), .QN (n_200));
  DFFNSRXL \instruction_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_172), .Q (UNCONNECTED29), .QN (n_198));
  DFFNSRXL \instruction_reg[8] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_252), .Q (instruction[8]), .QN (UNCONNECTED30));
  DFFNSRXL \instruction_reg[9] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (n_238), .Q (instruction[9]), .QN (UNCONNECTED31));
  INVX12 g2304(.A (n_200), .Y (instruction[6]));
  INVX12 g2308(.A (n_199), .Y (instruction[24]));
  INVX12 g2310(.A (n_198), .Y (instruction[7]));
  INVX12 g2313(.A (n_197), .Y (instruction[5]));
  INVX12 g2315(.A (n_196), .Y (instruction[4]));
  INVX12 g2319(.A (n_195), .Y (instruction[3]));
  INVX12 g2323(.A (n_194), .Y (instruction[1]));
  INVX12 g2325(.A (n_193), .Y (instruction[0]));
  INVX4 g2328(.A (n_192), .Y (instruction[2]));
  INVX12 g2332(.A (n_191), .Y (instruction[25]));
  NAND4X1 g2338(.A (n_107), .B (n_109), .C (n_111), .D (n_113), .Y
       (n_187));
  NAND4X1 g2349(.A (n_45), .B (n_49), .C (n_58), .D (n_66), .Y (n_176));
  NAND4X1 g2353(.A (n_48), .B (n_50), .C (n_51), .D (n_54), .Y (n_172));
  AND2X1 g2357(.A (n_115), .B (n_112), .Y (n_168));
  AND2X1 g2360(.A (n_124), .B (n_126), .Y (n_165));
  AND2X1 g2364(.A (n_116), .B (n_114), .Y (n_161));
  AND2X1 g2365(.A (n_110), .B (n_104), .Y (n_160));
  AND2X1 g2369(.A (n_99), .B (n_97), .Y (n_156));
  AND2X1 g2370(.A (n_101), .B (n_100), .Y (n_155));
  AND2X1 g2371(.A (n_96), .B (n_98), .Y (n_154));
  AND2X1 g2372(.A (n_88), .B (n_93), .Y (n_153));
  AND2X1 g2377(.A (n_130), .B (n_85), .Y (n_148));
  AND2X1 g2378(.A (n_84), .B (n_82), .Y (n_147));
  AND2X1 g2380(.A (n_81), .B (n_83), .Y (n_145));
  AND2X1 g2382(.A (n_74), .B (n_77), .Y (n_143));
  AND2X1 g2383(.A (n_75), .B (n_76), .Y (n_142));
  AND2X1 g2385(.A (n_43), .B (n_63), .Y (n_140));
  AND2X1 g2386(.A (n_67), .B (n_68), .Y (n_139));
  AND2X1 g2390(.A (n_57), .B (n_55), .Y (n_135));
  AND2X1 g2392(.A (n_56), .B (n_52), .Y (n_133));
  AND2X1 g2393(.A (n_86), .B (n_47), .Y (n_132));
  AND2X1 g2394(.A (n_44), .B (n_46), .Y (n_131));
  AOI22X1 g2395(.A0 (\addr2[31]_295 ), .A1 (n_10), .B0 (\addr3[31]_297
       ), .B1 (n_31), .Y (n_130));
  AOI22X1 g2396(.A0 (\addr1[8]_363 ), .A1 (n_16), .B0 (\addr2[8]_364 ),
       .B1 (n_9), .Y (n_129));
  AOI22X1 g2397(.A0 (\addr7[10]_351 ), .A1 (n_13), .B0 (\addr8[10]_352
       ), .B1 (n_3), .Y (n_128));
  AOI22X1 g2398(.A0 (\addr3[27]_464 ), .A1 (n_17), .B0 (\addr4[27]_465
       ), .B1 (n_2), .Y (n_127));
  AOI22X1 g2399(.A0 (\addr6[9]_359 ), .A1 (n_7), .B0 (\addr7[9]_360 ),
       .B1 (n_13), .Y (n_126));
  AOI22X1 g2400(.A0 (\addr1[27]_462 ), .A1 (n_42), .B0 (\addr2[27]_463
       ), .B1 (n_33), .Y (n_125));
  AOI22X1 g2401(.A0 (\addr5[9]_358 ), .A1 (n_1), .B0 (\addr8[9]_361 ),
       .B1 (n_37), .Y (n_124));
  AOI22X1 g2402(.A0 (\addr3[9]_356 ), .A1 (n_32), .B0 (\addr4[9]_357 ),
       .B1 (n_2), .Y (n_123));
  AOI22X1 g2403(.A0 (\addr1[9]_354 ), .A1 (n_16), .B0 (\addr2[9]_355 ),
       .B1 (n_9), .Y (n_122));
  AOI22X1 g2404(.A0 (\addr7[18]_315 ), .A1 (n_12), .B0 (\addr8[18]_316
       ), .B1 (n_36), .Y (n_121));
  AOI22X1 g2405(.A0 (\addr3[18]_311 ), .A1 (n_31), .B0 (\addr4[18]_312
       ), .B1 (n_40), .Y (n_120));
  AOI22X1 g2406(.A0 (\addr7[28]_459 ), .A1 (n_13), .B0 (\addr8[28]_460
       ), .B1 (n_37), .Y (n_119));
  AOI22X1 g2407(.A0 (\addr5[28]_457 ), .A1 (n_27), .B0 (\addr6[28]_458
       ), .B1 (n_38), .Y (n_118));
  AOI22X1 g2408(.A0 (\addr5[10]_349 ), .A1 (n_27), .B0 (\addr6[10]_350
       ), .B1 (n_5), .Y (n_117));
  AOI22X1 g2409(.A0 (\addr2[28]_454 ), .A1 (n_10), .B0 (\addr3[28]_455
       ), .B1 (n_32), .Y (n_116));
  AOI22X1 g2410(.A0 (\addr2[18]_310 ), .A1 (n_33), .B0 (\addr6[18]_314
       ), .B1 (n_6), .Y (n_115));
  AOI22X1 g2411(.A0 (\addr1[28]_453 ), .A1 (n_16), .B0 (\addr4[28]_456
       ), .B1 (n_41), .Y (n_114));
  AOI22X1 g2412(.A0 (\addr3[29]_419 ), .A1 (n_17), .B0 (\addr4[29]_420
       ), .B1 (n_40), .Y (n_113));
  AOI22X1 g2413(.A0 (\addr1[18]_309 ), .A1 (n_15), .B0 (\addr5[18]_313
       ), .B1 (n_28), .Y (n_112));
  AOI22X1 g2414(.A0 (\addr5[29]_421 ), .A1 (n_29), .B0 (\addr6[29]_422
       ), .B1 (n_7), .Y (n_111));
  AOI22X1 g2415(.A0 (\addr2[10]_346 ), .A1 (n_10), .B0 (\addr3[10]_347
       ), .B1 (n_32), .Y (n_110));
  AOI22X1 g2416(.A0 (\addr2[29]_418 ), .A1 (n_33), .B0 (\addr7[29]_423
       ), .B1 (n_13), .Y (n_109));
  AOI22X1 g2417(.A0 (\addr5[0]_448 ), .A1 (n_27), .B0 (\addr6[0]_449 ),
       .B1 (n_7), .Y (n_108));
  AOI22X1 g2418(.A0 (\addr1[29]_417 ), .A1 (n_42), .B0 (\addr8[29]_424
       ), .B1 (n_36), .Y (n_107));
  AOI22X1 g2419(.A0 (\addr7[1]_441 ), .A1 (n_34), .B0 (\addr8[1]_442 ),
       .B1 (n_3), .Y (n_106));
  AOI22X1 g2420(.A0 (\addr7[2]_432 ), .A1 (n_13), .B0 (\addr8[2]_433 ),
       .B1 (n_3), .Y (n_105));
  AOI22X1 g2421(.A0 (\addr1[10]_345 ), .A1 (n_16), .B0 (\addr4[10]_348
       ), .B1 (n_2), .Y (n_104));
  AOI22X1 g2422(.A0 (\addr3[2]_428 ), .A1 (n_31), .B0 (\addr4[2]_429 ),
       .B1 (n_41), .Y (n_103));
  AOI22X1 g2423(.A0 (\addr5[1]_439 ), .A1 (n_27), .B0 (\addr6[1]_440 ),
       .B1 (n_6), .Y (n_102));
  AOI22X1 g2424(.A0 (\addr2[2]_427 ), .A1 (n_10), .B0 (\addr6[2]_431 ),
       .B1 (n_5), .Y (n_101));
  AOI22X1 g2425(.A0 (\addr1[2]_426 ), .A1 (n_15), .B0 (\addr5[2]_430 ),
       .B1 (n_28), .Y (n_100));
  AOI22X1 g2426(.A0 (\addr2[1]_436 ), .A1 (n_33), .B0 (\addr3[1]_437 ),
       .B1 (n_31), .Y (n_99));
  AOI22X1 g2427(.A0 (\addr3[30]_338 ), .A1 (n_32), .B0 (\addr6[30]_341
       ), .B1 (n_7), .Y (n_98));
  AOI22X1 g2428(.A0 (\addr1[1]_435 ), .A1 (n_15), .B0 (\addr4[1]_438 ),
       .B1 (n_40), .Y (n_97));
  AOI22X1 g2429(.A0 (\addr5[30]_340 ), .A1 (n_27), .B0 (\addr4[30]_339
       ), .B1 (n_2), .Y (n_96));
  AOI22X1 g2430(.A0 (\addr7[30]_342 ), .A1 (n_12), .B0 (\addr8[30]_343
       ), .B1 (n_37), .Y (n_95));
  AOI22X1 g2431(.A0 (\addr1[30]_336 ), .A1 (n_16), .B0 (\addr2[30]_337
       ), .B1 (n_9), .Y (n_94));
  AOI22X1 g2432(.A0 (\addr3[16]_329 ), .A1 (n_31), .B0 (\addr6[16]_332
       ), .B1 (n_5), .Y (n_93));
  AOI22X1 g2433(.A0 (\addr7[24]_495 ), .A1 (n_13), .B0 (\addr8[24]_496
       ), .B1 (n_36), .Y (n_92));
  AOI22X1 g2434(.A0 (\addr7[31]_305 ), .A1 (n_34), .B0 (\addr8[31]_307
       ), .B1 (n_37), .Y (n_91));
  AOI22X1 g2435(.A0 (\addr3[24]_491 ), .A1 (n_31), .B0 (\addr4[24]_492
       ), .B1 (n_40), .Y (n_90));
  AOI22X1 g2436(.A0 (\addr5[31]_301 ), .A1 (n_27), .B0 (\addr6[31]_303
       ), .B1 (n_6), .Y (n_89));
  AOI22X1 g2437(.A0 (\addr5[16]_331 ), .A1 (n_28), .B0 (\addr4[16]_330
       ), .B1 (n_41), .Y (n_88));
  AOI22X1 g2438(.A0 (\addr7[8]_369 ), .A1 (n_12), .B0 (\addr8[8]_370 ),
       .B1 (n_3), .Y (n_87));
  AOI22X1 g2439(.A0 (\addr5[27]_466 ), .A1 (n_1), .B0 (\addr8[27]_469
       ), .B1 (n_37), .Y (n_86));
  AOI22X1 g2440(.A0 (\addr1[31]_293 ), .A1 (n_42), .B0 (\addr4[31]_299
       ), .B1 (n_40), .Y (n_85));
  AOI22X1 g2441(.A0 (\addr2[24]_490 ), .A1 (n_10), .B0 (\addr6[24]_494
       ), .B1 (n_6), .Y (n_84));
  AOI22X1 g2442(.A0 (\addr3[3]_410 ), .A1 (n_32), .B0 (\addr6[3]_413 ),
       .B1 (n_7), .Y (n_83));
  AOI22X1 g2443(.A0 (\addr1[24]_489 ), .A1 (n_16), .B0 (\addr5[24]_493
       ), .B1 (n_28), .Y (n_82));
  AOI22X1 g2444(.A0 (\addr5[3]_412 ), .A1 (n_28), .B0 (\addr4[3]_411 ),
       .B1 (n_41), .Y (n_81));
  AOI22X1 g2445(.A0 (\addr7[16]_333 ), .A1 (n_12), .B0 (\addr8[16]_334
       ), .B1 (n_36), .Y (n_80));
  AOI22X1 g2446(.A0 (\addr7[3]_414 ), .A1 (n_13), .B0 (\addr8[3]_415 ),
       .B1 (n_37), .Y (n_79));
  AOI22X1 g2447(.A0 (\addr1[3]_408 ), .A1 (n_16), .B0 (\addr2[3]_409 ),
       .B1 (n_33), .Y (n_78));
  AOI22X1 g2448(.A0 (\addr6[25]_485 ), .A1 (n_6), .B0 (\addr7[25]_486
       ), .B1 (n_34), .Y (n_77));
  AOI22X1 g2449(.A0 (\addr4[4]_402 ), .A1 (n_41), .B0 (\addr8[4]_406 ),
       .B1 (n_36), .Y (n_76));
  AOI22X1 g2450(.A0 (\addr3[4]_401 ), .A1 (n_32), .B0 (\addr7[4]_405 ),
       .B1 (n_34), .Y (n_75));
  AOI22X1 g2451(.A0 (\addr5[25]_484 ), .A1 (n_28), .B0 (\addr8[25]_487
       ), .B1 (n_36), .Y (n_74));
  AOI22X1 g2452(.A0 (\addr5[4]_403 ), .A1 (n_27), .B0 (\addr6[4]_404 ),
       .B1 (n_38), .Y (n_73));
  AOI22X1 g2453(.A0 (\addr1[4]_399 ), .A1 (n_15), .B0 (\addr2[4]_400 ),
       .B1 (n_10), .Y (n_72));
  AOI22X1 g2454(.A0 (\addr1[16]_327 ), .A1 (n_42), .B0 (\addr2[16]_328
       ), .B1 (n_10), .Y (n_71));
  AOI22X1 g2455(.A0 (\addr3[25]_482 ), .A1 (n_17), .B0 (\addr4[25]_483
       ), .B1 (n_41), .Y (n_70));
  AOI22X1 g2456(.A0 (\addr1[25]_480 ), .A1 (n_42), .B0 (\addr2[25]_481
       ), .B1 (n_10), .Y (n_69));
  AOI22X1 g2457(.A0 (\addr3[5]_392 ), .A1 (n_32), .B0 (\addr6[5]_395 ),
       .B1 (n_38), .Y (n_68));
  AOI22X1 g2458(.A0 (\addr5[5]_394 ), .A1 (n_28), .B0 (\addr4[5]_393 ),
       .B1 (n_41), .Y (n_67));
  AOI22X1 g2459(.A0 (\addr3[17]_320 ), .A1 (n_17), .B0 (\addr4[17]_321
       ), .B1 (n_40), .Y (n_66));
  AOI22X1 g2460(.A0 (\addr7[5]_396 ), .A1 (n_12), .B0 (\addr8[5]_397 ),
       .B1 (n_3), .Y (n_65));
  AOI22X1 g2461(.A0 (\addr1[5]_390 ), .A1 (n_16), .B0 (\addr2[5]_391 ),
       .B1 (n_9), .Y (n_64));
  AOI22X1 g2462(.A0 (\addr1[0]_444 ), .A1 (n_42), .B0 (\addr4[0]_447 ),
       .B1 (n_2), .Y (n_63));
  AOI22X1 g2463(.A0 (\addr7[26]_477 ), .A1 (n_13), .B0 (\addr8[26]_478
       ), .B1 (n_3), .Y (n_62));
  AOI22X1 g2464(.A0 (\addr3[26]_473 ), .A1 (n_31), .B0 (\addr4[26]_474
       ), .B1 (n_40), .Y (n_61));
  AOI22X1 g2465(.A0 (\addr7[6]_387 ), .A1 (n_34), .B0 (\addr8[6]_388 ),
       .B1 (n_37), .Y (n_60));
  AOI22X1 g2466(.A0 (\addr5[6]_385 ), .A1 (n_27), .B0 (\addr6[6]_386 ),
       .B1 (n_7), .Y (n_59));
  AOI22X1 g2467(.A0 (\addr5[17]_322 ), .A1 (n_29), .B0 (\addr6[17]_323
       ), .B1 (n_38), .Y (n_58));
  AOI22X1 g2468(.A0 (\addr2[6]_382 ), .A1 (n_9), .B0 (\addr3[6]_383 ),
       .B1 (n_32), .Y (n_57));
  AOI22X1 g2469(.A0 (\addr2[26]_472 ), .A1 (n_33), .B0 (\addr6[26]_476
       ), .B1 (n_5), .Y (n_56));
  AOI22X1 g2470(.A0 (\addr1[6]_381 ), .A1 (n_15), .B0 (\addr4[6]_384 ),
       .B1 (n_2), .Y (n_55));
  AOI22X1 g2471(.A0 (\addr3[7]_374 ), .A1 (n_17), .B0 (\addr4[7]_375 ),
       .B1 (n_40), .Y (n_54));
  AOI22X1 g2472(.A0 (\addr7[0]_450 ), .A1 (n_12), .B0 (\addr8[0]_451 ),
       .B1 (n_3), .Y (n_53));
  AOI22X1 g2473(.A0 (\addr1[26]_471 ), .A1 (n_15), .B0 (\addr5[26]_475
       ), .B1 (n_28), .Y (n_52));
  AOI22X1 g2474(.A0 (\addr5[7]_376 ), .A1 (n_29), .B0 (\addr6[7]_377 ),
       .B1 (n_6), .Y (n_51));
  AOI22X1 g2475(.A0 (\addr2[7]_373 ), .A1 (n_10), .B0 (\addr7[7]_378 ),
       .B1 (n_34), .Y (n_50));
  AOI22X1 g2476(.A0 (\addr2[17]_319 ), .A1 (n_10), .B0 (\addr7[17]_324
       ), .B1 (n_13), .Y (n_49));
  AOI22X1 g2477(.A0 (\addr1[7]_372 ), .A1 (n_16), .B0 (\addr8[7]_379 ),
       .B1 (n_36), .Y (n_48));
  AOI22X1 g2478(.A0 (\addr6[27]_467 ), .A1 (n_5), .B0 (\addr7[27]_468
       ), .B1 (n_13), .Y (n_47));
  AOI22X1 g2479(.A0 (\addr3[8]_365 ), .A1 (n_32), .B0 (\addr6[8]_368 ),
       .B1 (n_38), .Y (n_46));
  AOI22X1 g2480(.A0 (\addr1[17]_318 ), .A1 (n_16), .B0 (\addr8[17]_325
       ), .B1 (n_37), .Y (n_45));
  AOI22X1 g2481(.A0 (\addr5[8]_367 ), .A1 (n_28), .B0 (\addr4[8]_366 ),
       .B1 (n_2), .Y (n_44));
  AOI22X1 g2482(.A0 (\addr2[0]_445 ), .A1 (n_9), .B0 (\addr3[0]_446 ),
       .B1 (n_32), .Y (n_43));
  CLKINVX2 g2483(.A (n_39), .Y (n_41));
  INVX2 g2484(.A (n_39), .Y (n_40));
  INVX2 g2487(.A (n_35), .Y (n_37));
  INVX2 g2489(.A (n_35), .Y (n_36));
  INVX2 g2490(.A (n_30), .Y (n_32));
  INVX2 g2491(.A (n_30), .Y (n_31));
  INVX1 g2493(.A (n_30), .Y (n_17));
  INVX4 g2495(.A (n_26), .Y (n_28));
  INVX2 g2496(.A (n_26), .Y (n_27));
  INVX4 g2498(.A (n_29), .Y (n_26));
  NOR2X4 g2499(.A (Read_Addr[0]), .B (n_23), .Y (n_42));
  OR2X2 g2500(.A (n_20), .B (n_0), .Y (n_39));
  AND3X4 g2501(.A (Read_Addr[2]), .B (n_22), .C (Read_Addr[0]), .Y
       (n_38));
  OR2X1 g2502(.A (n_20), .B (n_25), .Y (n_35));
  NOR2X4 g2503(.A (Read_Addr[0]), .B (n_25), .Y (n_34));
  NOR2X4 g2504(.A (n_20), .B (n_23), .Y (n_33));
  OR2X2 g2505(.A (Read_Addr[0]), .B (n_0), .Y (n_30));
  NOR2X2 g2506(.A (Read_Addr[0]), .B (n_24), .Y (n_29));
  NAND2X1 g2507(.A (Read_Addr[1]), .B (Read_Addr[2]), .Y (n_25));
  NAND2X1 g2508(.A (Read_Addr[2]), .B (n_22), .Y (n_24));
  OR2X2 g2509(.A (Read_Addr[1]), .B (Read_Addr[2]), .Y (n_23));
  INVX2 g2512(.A (Read_Addr[1]), .Y (n_22));
  INVX2 g2513(.A (Read_Addr[0]), .Y (n_20));
  INVX3 drc_bufs2515(.A (n_14), .Y (n_16));
  INVX2 drc_bufs2517(.A (n_14), .Y (n_15));
  INVX2 drc_bufs2518(.A (n_42), .Y (n_14));
  INVX2 drc_bufs2523(.A (n_11), .Y (n_13));
  INVX1 drc_bufs2525(.A (n_11), .Y (n_12));
  INVX1 drc_bufs2526(.A (n_34), .Y (n_11));
  INVX3 drc_bufs2531(.A (n_8), .Y (n_10));
  INVX2 drc_bufs2533(.A (n_8), .Y (n_9));
  INVX2 drc_bufs2534(.A (n_33), .Y (n_8));
  INVX2 drc_bufs2539(.A (n_4), .Y (n_7));
  INVX2 drc_bufs2540(.A (n_4), .Y (n_6));
  INVX2 drc_bufs2541(.A (n_4), .Y (n_5));
  INVX1 drc_bufs2542(.A (n_38), .Y (n_4));
  INVX1 drc_bufs2547(.A (n_35), .Y (n_3));
  INVX2 drc_bufs2553(.A (n_39), .Y (n_2));
  BUFX2 drc_bufs2562(.A (n_28), .Y (n_1));
  NAND2BX1 g2(.AN (Read_Addr[2]), .B (Read_Addr[1]), .Y (n_0));
  NAND3X1 g2567(.A (n_103), .B (n_105), .C (n_155), .Y (n_234));
  NAND3X1 g2568(.A (n_120), .B (n_121), .C (n_168), .Y (n_235));
  NAND3X1 g2569(.A (n_118), .B (n_119), .C (n_161), .Y (n_236));
  NAND3X1 g2570(.A (n_102), .B (n_106), .C (n_156), .Y (n_237));
  NAND3X2 g2571(.A (n_122), .B (n_123), .C (n_165), .Y (n_238));
  NAND3X1 g2572(.A (n_94), .B (n_95), .C (n_154), .Y (n_239));
  NAND3X1 g2573(.A (n_71), .B (n_80), .C (n_153), .Y (n_240));
  NAND3X1 g2574(.A (n_90), .B (n_92), .C (n_147), .Y (n_241));
  NAND3X1 g2575(.A (n_89), .B (n_91), .C (n_148), .Y (n_242));
  NAND3X1 g2576(.A (n_78), .B (n_79), .C (n_145), .Y (n_243));
  NAND3X1 g2577(.A (n_61), .B (n_62), .C (n_133), .Y (n_244));
  NAND3X1 g2578(.A (n_72), .B (n_73), .C (n_142), .Y (n_245));
  NAND3X1 g2579(.A (n_64), .B (n_65), .C (n_139), .Y (n_246));
  NAND3X1 g2580(.A (n_108), .B (n_53), .C (n_140), .Y (n_247));
  NAND3X1 g2581(.A (n_69), .B (n_70), .C (n_143), .Y (n_248));
  NAND3X1 g2582(.A (n_59), .B (n_60), .C (n_135), .Y (n_249));
  NAND3X2 g2583(.A (n_125), .B (n_127), .C (n_132), .Y (n_250));
  NAND3X1 g2584(.A (n_117), .B (n_128), .C (n_160), .Y (n_251));
  NAND3X1 g2585(.A (n_129), .B (n_87), .C (n_131), .Y (n_252));
endmodule

module regfile8x8a(OUT1, OUT2, clk, INaddr, OUT1addr, OUT2addr, IN);
  input clk;
  input [2:0] INaddr, OUT1addr, OUT2addr;
  input [7:0] IN;
  output [7:0] OUT1, OUT2;
  wire clk;
  wire [2:0] INaddr, OUT1addr, OUT2addr;
  wire [7:0] IN;
  wire [7:0] OUT1, OUT2;
  wire [7:0] reg4;
  wire [7:0] reg5;
  wire [7:0] reg6;
  wire [7:0] reg7;
  wire [7:0] reg2;
  wire [7:0] reg1;
  wire [7:0] reg3;
  wire [7:0] reg0;
  wire UNCONNECTED32, UNCONNECTED33, UNCONNECTED34, UNCONNECTED35,
       UNCONNECTED36, UNCONNECTED37, UNCONNECTED38, UNCONNECTED39;
  wire UNCONNECTED40, UNCONNECTED41, UNCONNECTED42, UNCONNECTED43,
       UNCONNECTED44, UNCONNECTED45, UNCONNECTED46, UNCONNECTED47;
  wire UNCONNECTED48, UNCONNECTED49, UNCONNECTED50, UNCONNECTED51,
       UNCONNECTED52, UNCONNECTED53, UNCONNECTED54, UNCONNECTED55;
  wire UNCONNECTED56, UNCONNECTED57, UNCONNECTED58, UNCONNECTED59,
       UNCONNECTED60, UNCONNECTED61, UNCONNECTED62, UNCONNECTED63;
  wire UNCONNECTED64, UNCONNECTED65, UNCONNECTED66, UNCONNECTED67,
       UNCONNECTED68, UNCONNECTED69, UNCONNECTED70, UNCONNECTED71;
  wire UNCONNECTED72, UNCONNECTED73, UNCONNECTED74, UNCONNECTED75,
       UNCONNECTED76, UNCONNECTED77, UNCONNECTED78, UNCONNECTED79;
  wire UNCONNECTED80, UNCONNECTED81, UNCONNECTED82, UNCONNECTED83,
       UNCONNECTED84, UNCONNECTED85, UNCONNECTED86, UNCONNECTED87;
  wire UNCONNECTED88, UNCONNECTED89, UNCONNECTED90, UNCONNECTED91,
       UNCONNECTED92, UNCONNECTED93, UNCONNECTED94, UNCONNECTED95;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133;
  OR3X1 g2406(.A (n_89), .B (n_90), .C (n_114), .Y (n_133));
  OR3X1 g2407(.A (n_49), .B (n_69), .C (n_105), .Y (n_132));
  OR3X1 g2408(.A (n_84), .B (n_87), .C (n_116), .Y (n_131));
  OR3X1 g2409(.A (n_96), .B (n_94), .C (n_115), .Y (n_130));
  OR3X1 g2410(.A (n_39), .B (n_60), .C (n_113), .Y (n_129));
  OR3X1 g2411(.A (n_68), .B (n_70), .C (n_112), .Y (n_128));
  OR3X1 g2412(.A (n_82), .B (n_83), .C (n_117), .Y (n_127));
  OR3X1 g2413(.A (n_77), .B (n_78), .C (n_111), .Y (n_126));
  OR3X1 g2414(.A (n_66), .B (n_44), .C (n_109), .Y (n_125));
  OR3X1 g2415(.A (n_71), .B (n_53), .C (n_110), .Y (n_124));
  OR3X1 g2416(.A (n_59), .B (n_61), .C (n_107), .Y (n_123));
  OR3X1 g2417(.A (n_76), .B (n_88), .C (n_103), .Y (n_122));
  OR3X1 g2418(.A (n_56), .B (n_58), .C (n_108), .Y (n_121));
  OR3X1 g2419(.A (n_50), .B (n_51), .C (n_106), .Y (n_120));
  OR3X1 g2420(.A (n_43), .B (n_45), .C (n_104), .Y (n_119));
  OR3X1 g2421(.A (n_85), .B (n_38), .C (n_102), .Y (n_118));
  NAND2X1 g2422(.A (n_101), .B (n_86), .Y (n_117));
  NAND2X1 g2423(.A (n_95), .B (n_99), .Y (n_116));
  NAND2X1 g2424(.A (n_98), .B (n_100), .Y (n_115));
  NAND2X1 g2425(.A (n_91), .B (n_93), .Y (n_114));
  NAND2X1 g2426(.A (n_40), .B (n_57), .Y (n_113));
  NAND2X1 g2427(.A (n_75), .B (n_79), .Y (n_112));
  NAND2X1 g2428(.A (n_80), .B (n_81), .Y (n_111));
  NAND2X1 g2429(.A (n_73), .B (n_74), .Y (n_110));
  NAND2X1 g2430(.A (n_48), .B (n_52), .Y (n_109));
  NAND2X1 g2431(.A (n_62), .B (n_67), .Y (n_108));
  NAND2X1 g2432(.A (n_63), .B (n_64), .Y (n_107));
  NAND2X1 g2433(.A (n_54), .B (n_55), .Y (n_106));
  NAND2X1 g2434(.A (n_65), .B (n_72), .Y (n_105));
  NAND2X1 g2435(.A (n_47), .B (n_46), .Y (n_104));
  NAND2X1 g2436(.A (n_92), .B (n_97), .Y (n_103));
  NAND2X1 g2437(.A (n_41), .B (n_42), .Y (n_102));
  AOI22XL g2438(.A0 (reg4[1]), .A1 (n_33), .B0 (reg5[1]), .B1 (n_22),
       .Y (n_101));
  AOI22XL g2439(.A0 (reg6[3]), .A1 (n_23), .B0 (reg7[3]), .B1 (n_29),
       .Y (n_100));
  AOI22XL g2440(.A0 (reg4[1]), .A1 (n_36), .B0 (reg7[1]), .B1 (n_24),
       .Y (n_99));
  AOI22XL g2441(.A0 (reg4[3]), .A1 (n_33), .B0 (reg5[3]), .B1 (n_22),
       .Y (n_98));
  AOI22XL g2442(.A0 (reg6[4]), .A1 (n_26), .B0 (reg7[4]), .B1 (n_24),
       .Y (n_97));
  AO22XL g2443(.A0 (reg2[3]), .A1 (n_28), .B0 (reg1[3]), .B1 (n_30), .Y
       (n_96));
  AOI22XL g2444(.A0 (reg2[1]), .A1 (n_34), .B0 (reg3[1]), .B1 (n_27),
       .Y (n_95));
  AO22XL g2445(.A0 (reg0[3]), .A1 (n_25), .B0 (reg3[3]), .B1 (n_35), .Y
       (n_94));
  AOI22XL g2446(.A0 (reg2[2]), .A1 (n_28), .B0 (reg3[2]), .B1 (n_35),
       .Y (n_93));
  AOI22XL g2447(.A0 (reg2[4]), .A1 (n_34), .B0 (reg3[4]), .B1 (n_27),
       .Y (n_92));
  AOI22XL g2448(.A0 (reg4[2]), .A1 (n_33), .B0 (reg5[2]), .B1 (n_22),
       .Y (n_91));
  AO22XL g2449(.A0 (reg6[2]), .A1 (n_23), .B0 (reg7[2]), .B1 (n_29), .Y
       (n_90));
  AO22XL g2450(.A0 (reg0[2]), .A1 (n_25), .B0 (reg1[2]), .B1 (n_30), .Y
       (n_89));
  AO22XL g2451(.A0 (reg4[4]), .A1 (n_36), .B0 (reg5[4]), .B1 (n_37), .Y
       (n_88));
  AO22XL g2452(.A0 (reg6[1]), .A1 (n_26), .B0 (reg5[1]), .B1 (n_37), .Y
       (n_87));
  AOI22XL g2453(.A0 (reg2[1]), .A1 (n_28), .B0 (reg3[1]), .B1 (n_35),
       .Y (n_86));
  AO22XL g2454(.A0 (reg0[4]), .A1 (n_25), .B0 (reg1[4]), .B1 (n_30), .Y
       (n_85));
  AO22XL g2455(.A0 (reg0[1]), .A1 (n_32), .B0 (reg1[1]), .B1 (n_31), .Y
       (n_84));
  AO22XL g2456(.A0 (reg6[1]), .A1 (n_23), .B0 (reg7[1]), .B1 (n_29), .Y
       (n_83));
  AO22XL g2457(.A0 (reg0[1]), .A1 (n_25), .B0 (reg1[1]), .B1 (n_30), .Y
       (n_82));
  AOI22XL g2458(.A0 (reg5[0]), .A1 (n_22), .B0 (reg7[0]), .B1 (n_29),
       .Y (n_81));
  AOI22XL g2459(.A0 (reg2[0]), .A1 (n_28), .B0 (reg1[0]), .B1 (n_30),
       .Y (n_80));
  AOI22XL g2460(.A0 (reg6[0]), .A1 (n_26), .B0 (reg5[0]), .B1 (n_37),
       .Y (n_79));
  AO22XL g2461(.A0 (reg4[0]), .A1 (n_33), .B0 (reg3[0]), .B1 (n_35), .Y
       (n_78));
  AO22XL g2462(.A0 (reg0[0]), .A1 (n_25), .B0 (reg6[0]), .B1 (n_23), .Y
       (n_77));
  AO22XL g2463(.A0 (reg0[4]), .A1 (n_32), .B0 (reg1[4]), .B1 (n_31), .Y
       (n_76));
  AOI22XL g2464(.A0 (reg2[0]), .A1 (n_34), .B0 (reg7[0]), .B1 (n_24),
       .Y (n_75));
  AOI22XL g2465(.A0 (reg6[6]), .A1 (n_23), .B0 (reg7[6]), .B1 (n_29),
       .Y (n_74));
  AOI22XL g2466(.A0 (reg2[6]), .A1 (n_28), .B0 (reg1[6]), .B1 (n_30),
       .Y (n_73));
  AOI22XL g2467(.A0 (reg6[5]), .A1 (n_26), .B0 (reg5[5]), .B1 (n_37),
       .Y (n_72));
  AO22XL g2468(.A0 (reg4[6]), .A1 (n_33), .B0 (reg5[6]), .B1 (n_22), .Y
       (n_71));
  AO22XL g2469(.A0 (reg4[0]), .A1 (n_36), .B0 (reg3[0]), .B1 (n_27), .Y
       (n_70));
  AO22XL g2470(.A0 (reg3[5]), .A1 (n_27), .B0 (reg7[5]), .B1 (n_24), .Y
       (n_69));
  AO22XL g2471(.A0 (reg0[0]), .A1 (n_32), .B0 (reg1[0]), .B1 (n_31), .Y
       (n_68));
  AOI22XL g2472(.A0 (reg6[3]), .A1 (n_26), .B0 (reg3[3]), .B1 (n_27),
       .Y (n_67));
  AO22XL g2473(.A0 (reg0[2]), .A1 (n_32), .B0 (reg1[2]), .B1 (n_31), .Y
       (n_66));
  AOI22XL g2474(.A0 (reg4[5]), .A1 (n_36), .B0 (reg1[5]), .B1 (n_31),
       .Y (n_65));
  AOI22XL g2475(.A0 (reg4[6]), .A1 (n_36), .B0 (reg7[6]), .B1 (n_24),
       .Y (n_64));
  AOI22XL g2476(.A0 (reg2[6]), .A1 (n_34), .B0 (reg3[6]), .B1 (n_27),
       .Y (n_63));
  AOI22XL g2477(.A0 (reg0[3]), .A1 (n_32), .B0 (reg7[3]), .B1 (n_24),
       .Y (n_62));
  AO22XL g2478(.A0 (reg6[6]), .A1 (n_26), .B0 (reg5[6]), .B1 (n_37), .Y
       (n_61));
  AO22XL g2479(.A0 (reg4[7]), .A1 (n_36), .B0 (reg3[7]), .B1 (n_27), .Y
       (n_60));
  AO22XL g2480(.A0 (reg0[6]), .A1 (n_32), .B0 (reg1[6]), .B1 (n_31), .Y
       (n_59));
  AO22XL g2481(.A0 (reg4[3]), .A1 (n_36), .B0 (reg5[3]), .B1 (n_37), .Y
       (n_58));
  AOI22XL g2482(.A0 (reg6[7]), .A1 (n_26), .B0 (reg7[7]), .B1 (n_24),
       .Y (n_57));
  AO22XL g2483(.A0 (reg2[3]), .A1 (n_34), .B0 (reg1[3]), .B1 (n_31), .Y
       (n_56));
  AOI22XL g2484(.A0 (reg6[7]), .A1 (n_23), .B0 (reg7[7]), .B1 (n_29),
       .Y (n_55));
  AOI22XL g2485(.A0 (reg4[7]), .A1 (n_33), .B0 (reg5[7]), .B1 (n_22),
       .Y (n_54));
  AO22XL g2486(.A0 (reg0[6]), .A1 (n_25), .B0 (reg3[6]), .B1 (n_35), .Y
       (n_53));
  AOI22XL g2487(.A0 (reg4[2]), .A1 (n_36), .B0 (reg5[2]), .B1 (n_37),
       .Y (n_52));
  AO22XL g2488(.A0 (reg2[7]), .A1 (n_28), .B0 (reg3[7]), .B1 (n_35), .Y
       (n_51));
  AO22XL g2489(.A0 (reg0[7]), .A1 (n_25), .B0 (reg1[7]), .B1 (n_30), .Y
       (n_50));
  AO22XL g2490(.A0 (reg0[5]), .A1 (n_32), .B0 (reg2[5]), .B1 (n_34), .Y
       (n_49));
  AOI22XL g2491(.A0 (reg2[2]), .A1 (n_34), .B0 (reg3[2]), .B1 (n_27),
       .Y (n_48));
  AOI22XL g2492(.A0 (reg4[5]), .A1 (n_33), .B0 (reg5[5]), .B1 (n_22),
       .Y (n_47));
  AOI22XL g2493(.A0 (reg1[5]), .A1 (n_30), .B0 (reg3[5]), .B1 (n_35),
       .Y (n_46));
  AO22XL g2494(.A0 (reg6[5]), .A1 (n_23), .B0 (reg7[5]), .B1 (n_29), .Y
       (n_45));
  AO22XL g2495(.A0 (reg6[2]), .A1 (n_26), .B0 (reg7[2]), .B1 (n_24), .Y
       (n_44));
  AO22XL g2496(.A0 (reg0[5]), .A1 (n_25), .B0 (reg2[5]), .B1 (n_28), .Y
       (n_43));
  AOI22XL g2497(.A0 (reg6[4]), .A1 (n_23), .B0 (reg7[4]), .B1 (n_29),
       .Y (n_42));
  AOI22XL g2498(.A0 (reg4[4]), .A1 (n_33), .B0 (reg5[4]), .B1 (n_22),
       .Y (n_41));
  AOI22XL g2499(.A0 (reg1[7]), .A1 (n_31), .B0 (reg5[7]), .B1 (n_37),
       .Y (n_40));
  AO22XL g2500(.A0 (reg0[7]), .A1 (n_32), .B0 (reg2[7]), .B1 (n_34), .Y
       (n_39));
  AO22XL g2501(.A0 (reg2[4]), .A1 (n_28), .B0 (reg3[4]), .B1 (n_35), .Y
       (n_38));
  NOR2X1 g2502(.A (OUT1addr[1]), .B (n_17), .Y (n_37));
  NOR2X1 g2503(.A (OUT1addr[1]), .B (n_14), .Y (n_36));
  NOR2X1 g2504(.A (OUT2addr[2]), .B (n_18), .Y (n_35));
  AND2X1 g2505(.A (OUT1addr[1]), .B (n_15), .Y (n_34));
  AND2X1 g2506(.A (OUT2addr[2]), .B (n_19), .Y (n_33));
  NOR2BX1 g2507(.AN (n_15), .B (OUT1addr[1]), .Y (n_32));
  NOR2X1 g2508(.A (OUT1addr[1]), .B (n_16), .Y (n_31));
  NOR2X1 g2509(.A (OUT2addr[2]), .B (n_20), .Y (n_30));
  NOR2BX1 g2510(.AN (OUT2addr[2]), .B (n_18), .Y (n_29));
  NOR2X1 g2511(.A (OUT2addr[2]), .B (n_21), .Y (n_28));
  NOR2BX1 g2512(.AN (OUT1addr[1]), .B (n_16), .Y (n_27));
  NOR2BX1 g2513(.AN (OUT1addr[1]), .B (n_14), .Y (n_26));
  NOR2BX1 g2514(.AN (n_19), .B (OUT2addr[2]), .Y (n_25));
  NOR2BX1 g2515(.AN (OUT1addr[1]), .B (n_17), .Y (n_24));
  NOR2BX1 g2516(.AN (OUT2addr[2]), .B (n_21), .Y (n_23));
  NOR2BX1 g2517(.AN (OUT2addr[2]), .B (n_20), .Y (n_22));
  NAND2BX1 g2518(.AN (OUT2addr[0]), .B (OUT2addr[1]), .Y (n_21));
  NAND2BX1 g2519(.AN (OUT2addr[1]), .B (OUT2addr[0]), .Y (n_20));
  NOR2XL g2520(.A (OUT2addr[0]), .B (OUT2addr[1]), .Y (n_19));
  NAND2X1 g2521(.A (OUT2addr[1]), .B (OUT2addr[0]), .Y (n_18));
  NAND2X1 g2522(.A (OUT1addr[2]), .B (OUT1addr[0]), .Y (n_17));
  NAND2BX1 g2523(.AN (OUT1addr[2]), .B (OUT1addr[0]), .Y (n_16));
  NOR2XL g2524(.A (OUT1addr[0]), .B (OUT1addr[2]), .Y (n_15));
  NAND2BX1 g2525(.AN (OUT1addr[0]), .B (OUT1addr[2]), .Y (n_14));
  BUFX12 drc_bufs(.A (n_130), .Y (OUT2[3]));
  BUFX12 drc_bufs2526(.A (n_124), .Y (OUT2[6]));
  BUFX12 drc_bufs2527(.A (n_118), .Y (OUT2[4]));
  BUFX12 drc_bufs2528(.A (n_119), .Y (OUT2[5]));
  BUFX12 drc_bufs2529(.A (n_133), .Y (OUT2[2]));
  BUFX12 drc_bufs2530(.A (n_126), .Y (OUT2[0]));
  BUFX12 drc_bufs2531(.A (n_128), .Y (OUT1[0]));
  BUFX12 drc_bufs2532(.A (n_127), .Y (OUT2[1]));
  BUFX12 drc_bufs2533(.A (n_120), .Y (OUT2[7]));
  BUFX12 drc_bufs2534(.A (n_121), .Y (OUT1[3]));
  BUFX12 drc_bufs2535(.A (n_123), .Y (OUT1[6]));
  BUFX12 drc_bufs2536(.A (n_131), .Y (OUT1[1]));
  BUFX12 drc_bufs2537(.A (n_122), .Y (OUT1[4]));
  BUFX12 drc_bufs2538(.A (n_132), .Y (OUT1[5]));
  BUFX12 drc_bufs2539(.A (n_125), .Y (OUT1[2]));
  BUFX12 drc_bufs2540(.A (n_129), .Y (OUT1[7]));
  SDFFNSRX1 \reg6_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_9), .SI (reg6[2]), .Q (reg6[2]), .QN
       (UNCONNECTED32));
  SDFFNSRX1 \reg0_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_0), .SI (reg0[1]), .Q (reg0[1]), .QN
       (UNCONNECTED33));
  SDFFNSRX1 \reg1_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[3]), .SE (n_11), .SI (IN[3]), .Q (reg1[3]), .QN
       (UNCONNECTED34));
  SDFFNSRX1 \reg1_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[4]), .SE (n_11), .SI (IN[4]), .Q (reg1[4]), .QN
       (UNCONNECTED35));
  SDFFNSRX1 \reg5_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[2]), .SE (n_1), .SI (IN[2]), .Q (reg5[2]), .QN
       (UNCONNECTED36));
  SDFFNSRX1 \reg5_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[3]), .SE (n_1), .SI (IN[3]), .Q (reg5[3]), .QN
       (UNCONNECTED37));
  SDFFNSRX1 \reg5_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[4]), .SE (n_1), .SI (IN[4]), .Q (reg5[4]), .QN
       (UNCONNECTED38));
  SDFFNSRX1 \reg5_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[5]), .SE (n_1), .SI (IN[5]), .Q (reg5[5]), .QN
       (UNCONNECTED39));
  SDFFNSRX1 \reg1_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[5]), .SE (n_11), .SI (IN[5]), .Q (reg1[5]), .QN
       (UNCONNECTED40));
  SDFFNSRX1 \reg5_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[6]), .SE (n_1), .SI (IN[6]), .Q (reg5[6]), .QN
       (UNCONNECTED41));
  SDFFNSRX1 \reg5_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[7]), .SE (n_1), .SI (IN[7]), .Q (reg5[7]), .QN
       (UNCONNECTED42));
  SDFFNSRX1 \reg1_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[6]), .SE (n_11), .SI (IN[6]), .Q (reg1[6]), .QN
       (UNCONNECTED43));
  SDFFNSRX1 \reg6_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_9), .SI (reg6[0]), .Q (reg6[0]), .QN
       (UNCONNECTED44));
  SDFFNSRX1 \reg1_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[7]), .SE (n_11), .SI (IN[7]), .Q (reg1[7]), .QN
       (UNCONNECTED45));
  SDFFNSRX1 \reg2_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_13), .SI (reg2[0]), .Q (reg2[0]), .QN
       (UNCONNECTED46));
  SDFFNSRX1 \reg6_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_9), .SI (reg6[1]), .Q (reg6[1]), .QN
       (UNCONNECTED47));
  SDFFNSRX1 \reg0_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_0), .SI (reg0[0]), .Q (reg0[0]), .QN
       (UNCONNECTED48));
  SDFFNSRX1 \reg6_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_9), .SI (reg6[3]), .Q (reg6[3]), .QN
       (UNCONNECTED49));
  SDFFNSRX1 \reg6_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_9), .SI (reg6[4]), .Q (reg6[4]), .QN
       (UNCONNECTED50));
  SDFFNSRX1 \reg2_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_13), .SI (reg2[1]), .Q (reg2[1]), .QN
       (UNCONNECTED51));
  SDFFNSRX1 \reg6_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_9), .SI (reg6[5]), .Q (reg6[5]), .QN
       (UNCONNECTED52));
  SDFFNSRX1 \reg6_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_9), .SI (reg6[6]), .Q (reg6[6]), .QN
       (UNCONNECTED53));
  SDFFNSRX1 \reg2_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_13), .SI (reg2[2]), .Q (reg2[2]), .QN
       (UNCONNECTED54));
  SDFFNSRX1 \reg6_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_9), .SI (reg6[7]), .Q (reg6[7]), .QN
       (UNCONNECTED55));
  SDFFNSRX1 \reg7_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_10), .SI (reg7[0]), .Q (reg7[0]), .QN
       (UNCONNECTED56));
  SDFFNSRX1 \reg0_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_0), .SI (reg0[2]), .Q (reg0[2]), .QN
       (UNCONNECTED57));
  SDFFNSRX1 \reg2_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_13), .SI (reg2[3]), .Q (reg2[3]), .QN
       (UNCONNECTED58));
  SDFFNSRX1 \reg2_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_13), .SI (reg2[4]), .Q (reg2[4]), .QN
       (UNCONNECTED59));
  SDFFNSRX1 \reg7_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_10), .SI (reg7[1]), .Q (reg7[1]), .QN
       (UNCONNECTED60));
  SDFFNSRX1 \reg7_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_10), .SI (reg7[2]), .Q (reg7[2]), .QN
       (UNCONNECTED61));
  SDFFNSRX1 \reg7_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_10), .SI (reg7[3]), .Q (reg7[3]), .QN
       (UNCONNECTED62));
  SDFFNSRX1 \reg7_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_10), .SI (reg7[4]), .Q (reg7[4]), .QN
       (UNCONNECTED63));
  SDFFNSRX1 \reg0_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_0), .SI (reg0[6]), .Q (reg0[6]), .QN
       (UNCONNECTED64));
  SDFFNSRX1 \reg7_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_10), .SI (reg7[5]), .Q (reg7[5]), .QN
       (UNCONNECTED65));
  SDFFNSRX1 \reg7_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_10), .SI (reg7[6]), .Q (reg7[6]), .QN
       (UNCONNECTED66));
  SDFFNSRX1 \reg2_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_13), .SI (reg2[6]), .Q (reg2[6]), .QN
       (UNCONNECTED67));
  SDFFNSRX1 \reg7_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_10), .SI (reg7[7]), .Q (reg7[7]), .QN
       (UNCONNECTED68));
  SDFFNSRX1 \reg0_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_0), .SI (reg0[3]), .Q (reg0[3]), .QN
       (UNCONNECTED69));
  SDFFNSRX1 \reg2_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_13), .SI (reg2[7]), .Q (reg2[7]), .QN
       (UNCONNECTED70));
  SDFFNSRX1 \reg3_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_8), .SI (reg3[0]), .Q (reg3[0]), .QN
       (UNCONNECTED71));
  SDFFNSRX1 \reg3_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_8), .SI (reg3[1]), .Q (reg3[1]), .QN
       (UNCONNECTED72));
  SDFFNSRX1 \reg3_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_8), .SI (reg3[2]), .Q (reg3[2]), .QN
       (UNCONNECTED73));
  SDFFNSRX1 \reg0_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_0), .SI (reg0[4]), .Q (reg0[4]), .QN
       (UNCONNECTED74));
  SDFFNSRX1 \reg0_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_0), .SI (reg0[5]), .Q (reg0[5]), .QN
       (UNCONNECTED75));
  SDFFNSRX1 \reg3_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_8), .SI (reg3[3]), .Q (reg3[3]), .QN
       (UNCONNECTED76));
  SDFFNSRX1 \reg3_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_8), .SI (reg3[4]), .Q (reg3[4]), .QN
       (UNCONNECTED77));
  SDFFNSRX1 \reg3_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_8), .SI (reg3[5]), .Q (reg3[5]), .QN
       (UNCONNECTED78));
  SDFFNSRX1 \reg3_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_8), .SI (reg3[6]), .Q (reg3[6]), .QN
       (UNCONNECTED79));
  SDFFNSRX1 \reg2_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_13), .SI (reg2[5]), .Q (reg2[5]), .QN
       (UNCONNECTED80));
  SDFFNSRX1 \reg3_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_8), .SI (reg3[7]), .Q (reg3[7]), .QN
       (UNCONNECTED81));
  SDFFNSRX1 \reg0_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_0), .SI (reg0[7]), .Q (reg0[7]), .QN
       (UNCONNECTED82));
  SDFFNSRX1 \reg4_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[0]), .SE (n_12), .SI (IN[0]), .Q (reg4[0]), .QN
       (UNCONNECTED83));
  SDFFNSRX1 \reg4_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[1]), .SE (n_12), .SI (IN[1]), .Q (reg4[1]), .QN
       (UNCONNECTED84));
  SDFFNSRX1 \reg1_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[0]), .SE (n_11), .SI (IN[0]), .Q (reg1[0]), .QN
       (UNCONNECTED85));
  SDFFNSRX1 \reg4_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[2]), .SE (n_12), .SI (IN[2]), .Q (reg4[2]), .QN
       (UNCONNECTED86));
  SDFFNSRX1 \reg4_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[3]), .SE (n_12), .SI (IN[3]), .Q (reg4[3]), .QN
       (UNCONNECTED87));
  SDFFNSRX1 \reg4_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[4]), .SE (n_12), .SI (IN[4]), .Q (reg4[4]), .QN
       (UNCONNECTED88));
  SDFFNSRX1 \reg4_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[5]), .SE (n_12), .SI (IN[5]), .Q (reg4[5]), .QN
       (UNCONNECTED89));
  SDFFNSRX1 \reg1_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[1]), .SE (n_11), .SI (IN[1]), .Q (reg1[1]), .QN
       (UNCONNECTED90));
  SDFFNSRX1 \reg4_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[6]), .SE (n_12), .SI (IN[6]), .Q (reg4[6]), .QN
       (UNCONNECTED91));
  SDFFNSRX1 \reg4_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[7]), .SE (n_12), .SI (IN[7]), .Q (reg4[7]), .QN
       (UNCONNECTED92));
  SDFFNSRX1 \reg1_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[2]), .SE (n_11), .SI (IN[2]), .Q (reg1[2]), .QN
       (UNCONNECTED93));
  SDFFNSRX1 \reg5_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[0]), .SE (n_1), .SI (IN[0]), .Q (reg5[0]), .QN
       (UNCONNECTED94));
  SDFFNSRX1 \reg5_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[1]), .SE (n_1), .SI (IN[1]), .Q (reg5[1]), .QN
       (UNCONNECTED95));
  NAND2X2 g685(.A (INaddr[1]), .B (n_5), .Y (n_13));
  AND2X1 g686(.A (n_3), .B (n_7), .Y (n_12));
  AND2X1 g688(.A (n_3), .B (n_4), .Y (n_11));
  OR2X1 g689(.A (n_3), .B (n_6), .Y (n_10));
  NAND2X2 g690(.A (INaddr[1]), .B (n_7), .Y (n_9));
  NAND2X2 g692(.A (INaddr[1]), .B (n_4), .Y (n_8));
  NOR2BX1 g694(.AN (INaddr[2]), .B (INaddr[0]), .Y (n_7));
  NAND2X1 g695(.A (INaddr[0]), .B (INaddr[2]), .Y (n_6));
  NOR2XL g697(.A (INaddr[0]), .B (INaddr[2]), .Y (n_5));
  NOR2BX1 g698(.AN (INaddr[0]), .B (INaddr[2]), .Y (n_4));
  INVX1 g699(.A (INaddr[1]), .Y (n_3));
  NOR2BX2 g2(.AN (n_3), .B (n_6), .Y (n_1));
  NAND2BX2 g700(.AN (INaddr[1]), .B (n_5), .Y (n_0));
endmodule

module regfile8x8a_33(OUT1, OUT2, clk, INaddr, OUT1addr, OUT2addr, IN);
  input clk;
  input [2:0] INaddr, OUT1addr, OUT2addr;
  input [7:0] IN;
  output [7:0] OUT1, OUT2;
  wire clk;
  wire [2:0] INaddr, OUT1addr, OUT2addr;
  wire [7:0] IN;
  wire [7:0] OUT1, OUT2;
  wire [7:0] reg4;
  wire [7:0] reg5;
  wire [7:0] reg6;
  wire [7:0] reg7;
  wire [7:0] reg2;
  wire [7:0] reg1;
  wire [7:0] reg3;
  wire [7:0] reg0;
  wire UNCONNECTED96, UNCONNECTED97, UNCONNECTED98, UNCONNECTED99,
       UNCONNECTED100, UNCONNECTED101, UNCONNECTED102, UNCONNECTED103;
  wire UNCONNECTED104, UNCONNECTED105, UNCONNECTED106, UNCONNECTED107,
       UNCONNECTED108, UNCONNECTED109, UNCONNECTED110, UNCONNECTED111;
  wire UNCONNECTED112, UNCONNECTED113, UNCONNECTED114, UNCONNECTED115,
       UNCONNECTED116, UNCONNECTED117, UNCONNECTED118, UNCONNECTED119;
  wire UNCONNECTED120, UNCONNECTED121, UNCONNECTED122, UNCONNECTED123,
       UNCONNECTED124, UNCONNECTED125, UNCONNECTED126, UNCONNECTED127;
  wire UNCONNECTED128, UNCONNECTED129, UNCONNECTED130, UNCONNECTED131,
       UNCONNECTED132, UNCONNECTED133, UNCONNECTED134, UNCONNECTED135;
  wire UNCONNECTED136, UNCONNECTED137, UNCONNECTED138, UNCONNECTED139,
       UNCONNECTED140, UNCONNECTED141, UNCONNECTED142, UNCONNECTED143;
  wire UNCONNECTED144, UNCONNECTED145, UNCONNECTED146, UNCONNECTED147,
       UNCONNECTED148, UNCONNECTED149, UNCONNECTED150, UNCONNECTED151;
  wire UNCONNECTED152, UNCONNECTED153, UNCONNECTED154, UNCONNECTED155,
       UNCONNECTED156, UNCONNECTED157, UNCONNECTED158, UNCONNECTED159;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133;
  OR3X1 g2406(.A (n_89), .B (n_90), .C (n_114), .Y (n_133));
  OR3X1 g2407(.A (n_49), .B (n_69), .C (n_105), .Y (n_132));
  OR3X1 g2408(.A (n_84), .B (n_87), .C (n_116), .Y (n_131));
  OR3X1 g2409(.A (n_96), .B (n_94), .C (n_115), .Y (n_130));
  OR3X1 g2410(.A (n_39), .B (n_60), .C (n_113), .Y (n_129));
  OR3X1 g2411(.A (n_68), .B (n_70), .C (n_112), .Y (n_128));
  OR3X1 g2412(.A (n_82), .B (n_83), .C (n_117), .Y (n_127));
  OR3X1 g2413(.A (n_77), .B (n_78), .C (n_111), .Y (n_126));
  OR3X1 g2414(.A (n_66), .B (n_44), .C (n_109), .Y (n_125));
  OR3X1 g2415(.A (n_71), .B (n_53), .C (n_110), .Y (n_124));
  OR3X1 g2416(.A (n_59), .B (n_61), .C (n_107), .Y (n_123));
  OR3X1 g2417(.A (n_76), .B (n_88), .C (n_103), .Y (n_122));
  OR3X1 g2418(.A (n_56), .B (n_58), .C (n_108), .Y (n_121));
  OR3X1 g2419(.A (n_50), .B (n_51), .C (n_106), .Y (n_120));
  OR3X1 g2420(.A (n_43), .B (n_45), .C (n_104), .Y (n_119));
  OR3X1 g2421(.A (n_85), .B (n_38), .C (n_102), .Y (n_118));
  NAND2X1 g2422(.A (n_101), .B (n_86), .Y (n_117));
  NAND2X1 g2423(.A (n_95), .B (n_99), .Y (n_116));
  NAND2X1 g2424(.A (n_98), .B (n_100), .Y (n_115));
  NAND2X1 g2425(.A (n_91), .B (n_93), .Y (n_114));
  NAND2X1 g2426(.A (n_40), .B (n_57), .Y (n_113));
  NAND2X1 g2427(.A (n_75), .B (n_79), .Y (n_112));
  NAND2X1 g2428(.A (n_80), .B (n_81), .Y (n_111));
  NAND2X1 g2429(.A (n_73), .B (n_74), .Y (n_110));
  NAND2X1 g2430(.A (n_48), .B (n_52), .Y (n_109));
  NAND2X1 g2431(.A (n_62), .B (n_67), .Y (n_108));
  NAND2X1 g2432(.A (n_63), .B (n_64), .Y (n_107));
  NAND2X1 g2433(.A (n_54), .B (n_55), .Y (n_106));
  NAND2X1 g2434(.A (n_65), .B (n_72), .Y (n_105));
  NAND2X1 g2435(.A (n_47), .B (n_46), .Y (n_104));
  NAND2X1 g2436(.A (n_92), .B (n_97), .Y (n_103));
  NAND2X1 g2437(.A (n_41), .B (n_42), .Y (n_102));
  AOI22XL g2438(.A0 (reg4[1]), .A1 (n_33), .B0 (reg5[1]), .B1 (n_22),
       .Y (n_101));
  AOI22XL g2439(.A0 (reg6[3]), .A1 (n_23), .B0 (reg7[3]), .B1 (n_29),
       .Y (n_100));
  AOI22XL g2440(.A0 (reg4[1]), .A1 (n_36), .B0 (reg7[1]), .B1 (n_24),
       .Y (n_99));
  AOI22XL g2441(.A0 (reg4[3]), .A1 (n_33), .B0 (reg5[3]), .B1 (n_22),
       .Y (n_98));
  AOI22XL g2442(.A0 (reg6[4]), .A1 (n_26), .B0 (reg7[4]), .B1 (n_24),
       .Y (n_97));
  AO22XL g2443(.A0 (reg2[3]), .A1 (n_28), .B0 (reg1[3]), .B1 (n_30), .Y
       (n_96));
  AOI22XL g2444(.A0 (reg2[1]), .A1 (n_34), .B0 (reg3[1]), .B1 (n_27),
       .Y (n_95));
  AO22XL g2445(.A0 (reg0[3]), .A1 (n_25), .B0 (reg3[3]), .B1 (n_35), .Y
       (n_94));
  AOI22XL g2446(.A0 (reg2[2]), .A1 (n_28), .B0 (reg3[2]), .B1 (n_35),
       .Y (n_93));
  AOI22XL g2447(.A0 (reg2[4]), .A1 (n_34), .B0 (reg3[4]), .B1 (n_27),
       .Y (n_92));
  AOI22XL g2448(.A0 (reg4[2]), .A1 (n_33), .B0 (reg5[2]), .B1 (n_22),
       .Y (n_91));
  AO22XL g2449(.A0 (reg6[2]), .A1 (n_23), .B0 (reg7[2]), .B1 (n_29), .Y
       (n_90));
  AO22XL g2450(.A0 (reg0[2]), .A1 (n_25), .B0 (reg1[2]), .B1 (n_30), .Y
       (n_89));
  AO22XL g2451(.A0 (reg4[4]), .A1 (n_36), .B0 (reg5[4]), .B1 (n_37), .Y
       (n_88));
  AO22XL g2452(.A0 (reg6[1]), .A1 (n_26), .B0 (reg5[1]), .B1 (n_37), .Y
       (n_87));
  AOI22XL g2453(.A0 (reg2[1]), .A1 (n_28), .B0 (reg3[1]), .B1 (n_35),
       .Y (n_86));
  AO22XL g2454(.A0 (reg0[4]), .A1 (n_25), .B0 (reg1[4]), .B1 (n_30), .Y
       (n_85));
  AO22XL g2455(.A0 (reg0[1]), .A1 (n_32), .B0 (reg1[1]), .B1 (n_31), .Y
       (n_84));
  AO22XL g2456(.A0 (reg6[1]), .A1 (n_23), .B0 (reg7[1]), .B1 (n_29), .Y
       (n_83));
  AO22XL g2457(.A0 (reg0[1]), .A1 (n_25), .B0 (reg1[1]), .B1 (n_30), .Y
       (n_82));
  AOI22XL g2458(.A0 (reg5[0]), .A1 (n_22), .B0 (reg7[0]), .B1 (n_29),
       .Y (n_81));
  AOI22XL g2459(.A0 (reg2[0]), .A1 (n_28), .B0 (reg1[0]), .B1 (n_30),
       .Y (n_80));
  AOI22XL g2460(.A0 (reg6[0]), .A1 (n_26), .B0 (reg5[0]), .B1 (n_37),
       .Y (n_79));
  AO22XL g2461(.A0 (reg4[0]), .A1 (n_33), .B0 (reg3[0]), .B1 (n_35), .Y
       (n_78));
  AO22XL g2462(.A0 (reg0[0]), .A1 (n_25), .B0 (reg6[0]), .B1 (n_23), .Y
       (n_77));
  AO22XL g2463(.A0 (reg0[4]), .A1 (n_32), .B0 (reg1[4]), .B1 (n_31), .Y
       (n_76));
  AOI22XL g2464(.A0 (reg2[0]), .A1 (n_34), .B0 (reg7[0]), .B1 (n_24),
       .Y (n_75));
  AOI22XL g2465(.A0 (reg6[6]), .A1 (n_23), .B0 (reg7[6]), .B1 (n_29),
       .Y (n_74));
  AOI22XL g2466(.A0 (reg2[6]), .A1 (n_28), .B0 (reg1[6]), .B1 (n_30),
       .Y (n_73));
  AOI22XL g2467(.A0 (reg6[5]), .A1 (n_26), .B0 (reg5[5]), .B1 (n_37),
       .Y (n_72));
  AO22XL g2468(.A0 (reg4[6]), .A1 (n_33), .B0 (reg5[6]), .B1 (n_22), .Y
       (n_71));
  AO22XL g2469(.A0 (reg4[0]), .A1 (n_36), .B0 (reg3[0]), .B1 (n_27), .Y
       (n_70));
  AO22XL g2470(.A0 (reg3[5]), .A1 (n_27), .B0 (reg7[5]), .B1 (n_24), .Y
       (n_69));
  AO22XL g2471(.A0 (reg0[0]), .A1 (n_32), .B0 (reg1[0]), .B1 (n_31), .Y
       (n_68));
  AOI22XL g2472(.A0 (reg6[3]), .A1 (n_26), .B0 (reg3[3]), .B1 (n_27),
       .Y (n_67));
  AO22XL g2473(.A0 (reg0[2]), .A1 (n_32), .B0 (reg1[2]), .B1 (n_31), .Y
       (n_66));
  AOI22XL g2474(.A0 (reg4[5]), .A1 (n_36), .B0 (reg1[5]), .B1 (n_31),
       .Y (n_65));
  AOI22XL g2475(.A0 (reg4[6]), .A1 (n_36), .B0 (reg7[6]), .B1 (n_24),
       .Y (n_64));
  AOI22XL g2476(.A0 (reg2[6]), .A1 (n_34), .B0 (reg3[6]), .B1 (n_27),
       .Y (n_63));
  AOI22XL g2477(.A0 (reg0[3]), .A1 (n_32), .B0 (reg7[3]), .B1 (n_24),
       .Y (n_62));
  AO22XL g2478(.A0 (reg6[6]), .A1 (n_26), .B0 (reg5[6]), .B1 (n_37), .Y
       (n_61));
  AO22XL g2479(.A0 (reg4[7]), .A1 (n_36), .B0 (reg3[7]), .B1 (n_27), .Y
       (n_60));
  AO22XL g2480(.A0 (reg0[6]), .A1 (n_32), .B0 (reg1[6]), .B1 (n_31), .Y
       (n_59));
  AO22XL g2481(.A0 (reg4[3]), .A1 (n_36), .B0 (reg5[3]), .B1 (n_37), .Y
       (n_58));
  AOI22XL g2482(.A0 (reg6[7]), .A1 (n_26), .B0 (reg7[7]), .B1 (n_24),
       .Y (n_57));
  AO22XL g2483(.A0 (reg2[3]), .A1 (n_34), .B0 (reg1[3]), .B1 (n_31), .Y
       (n_56));
  AOI22XL g2484(.A0 (reg6[7]), .A1 (n_23), .B0 (reg7[7]), .B1 (n_29),
       .Y (n_55));
  AOI22XL g2485(.A0 (reg4[7]), .A1 (n_33), .B0 (reg5[7]), .B1 (n_22),
       .Y (n_54));
  AO22XL g2486(.A0 (reg0[6]), .A1 (n_25), .B0 (reg3[6]), .B1 (n_35), .Y
       (n_53));
  AOI22XL g2487(.A0 (reg4[2]), .A1 (n_36), .B0 (reg5[2]), .B1 (n_37),
       .Y (n_52));
  AO22XL g2488(.A0 (reg2[7]), .A1 (n_28), .B0 (reg3[7]), .B1 (n_35), .Y
       (n_51));
  AO22XL g2489(.A0 (reg0[7]), .A1 (n_25), .B0 (reg1[7]), .B1 (n_30), .Y
       (n_50));
  AO22XL g2490(.A0 (reg0[5]), .A1 (n_32), .B0 (reg2[5]), .B1 (n_34), .Y
       (n_49));
  AOI22XL g2491(.A0 (reg2[2]), .A1 (n_34), .B0 (reg3[2]), .B1 (n_27),
       .Y (n_48));
  AOI22XL g2492(.A0 (reg4[5]), .A1 (n_33), .B0 (reg5[5]), .B1 (n_22),
       .Y (n_47));
  AOI22XL g2493(.A0 (reg1[5]), .A1 (n_30), .B0 (reg3[5]), .B1 (n_35),
       .Y (n_46));
  AO22XL g2494(.A0 (reg6[5]), .A1 (n_23), .B0 (reg7[5]), .B1 (n_29), .Y
       (n_45));
  AO22XL g2495(.A0 (reg6[2]), .A1 (n_26), .B0 (reg7[2]), .B1 (n_24), .Y
       (n_44));
  AO22XL g2496(.A0 (reg0[5]), .A1 (n_25), .B0 (reg2[5]), .B1 (n_28), .Y
       (n_43));
  AOI22XL g2497(.A0 (reg6[4]), .A1 (n_23), .B0 (reg7[4]), .B1 (n_29),
       .Y (n_42));
  AOI22XL g2498(.A0 (reg4[4]), .A1 (n_33), .B0 (reg5[4]), .B1 (n_22),
       .Y (n_41));
  AOI22XL g2499(.A0 (reg1[7]), .A1 (n_31), .B0 (reg5[7]), .B1 (n_37),
       .Y (n_40));
  AO22XL g2500(.A0 (reg0[7]), .A1 (n_32), .B0 (reg2[7]), .B1 (n_34), .Y
       (n_39));
  AO22XL g2501(.A0 (reg2[4]), .A1 (n_28), .B0 (reg3[4]), .B1 (n_35), .Y
       (n_38));
  NOR2X1 g2502(.A (OUT1addr[1]), .B (n_17), .Y (n_37));
  NOR2X1 g2503(.A (OUT1addr[1]), .B (n_14), .Y (n_36));
  NOR2X1 g2504(.A (OUT2addr[2]), .B (n_18), .Y (n_35));
  AND2X1 g2505(.A (OUT1addr[1]), .B (n_15), .Y (n_34));
  AND2X1 g2506(.A (OUT2addr[2]), .B (n_19), .Y (n_33));
  NOR2BX1 g2507(.AN (n_15), .B (OUT1addr[1]), .Y (n_32));
  NOR2X1 g2508(.A (OUT1addr[1]), .B (n_16), .Y (n_31));
  NOR2X1 g2509(.A (OUT2addr[2]), .B (n_20), .Y (n_30));
  NOR2BX1 g2510(.AN (OUT2addr[2]), .B (n_18), .Y (n_29));
  NOR2X1 g2511(.A (OUT2addr[2]), .B (n_21), .Y (n_28));
  NOR2BX1 g2512(.AN (OUT1addr[1]), .B (n_16), .Y (n_27));
  NOR2BX1 g2513(.AN (OUT1addr[1]), .B (n_14), .Y (n_26));
  NOR2BX1 g2514(.AN (n_19), .B (OUT2addr[2]), .Y (n_25));
  NOR2BX1 g2515(.AN (OUT1addr[1]), .B (n_17), .Y (n_24));
  NOR2BX1 g2516(.AN (OUT2addr[2]), .B (n_21), .Y (n_23));
  NOR2BX1 g2517(.AN (OUT2addr[2]), .B (n_20), .Y (n_22));
  NAND2BX1 g2518(.AN (OUT2addr[0]), .B (OUT2addr[1]), .Y (n_21));
  NAND2BX1 g2519(.AN (OUT2addr[1]), .B (OUT2addr[0]), .Y (n_20));
  NOR2XL g2520(.A (OUT2addr[0]), .B (OUT2addr[1]), .Y (n_19));
  NAND2X1 g2521(.A (OUT2addr[1]), .B (OUT2addr[0]), .Y (n_18));
  NAND2X1 g2522(.A (OUT1addr[2]), .B (OUT1addr[0]), .Y (n_17));
  NAND2BX1 g2523(.AN (OUT1addr[2]), .B (OUT1addr[0]), .Y (n_16));
  NOR2XL g2524(.A (OUT1addr[0]), .B (OUT1addr[2]), .Y (n_15));
  NAND2BX1 g2525(.AN (OUT1addr[0]), .B (OUT1addr[2]), .Y (n_14));
  BUFX12 drc_bufs(.A (n_130), .Y (OUT2[3]));
  BUFX12 drc_bufs2526(.A (n_124), .Y (OUT2[6]));
  BUFX12 drc_bufs2527(.A (n_118), .Y (OUT2[4]));
  BUFX12 drc_bufs2528(.A (n_119), .Y (OUT2[5]));
  BUFX12 drc_bufs2529(.A (n_133), .Y (OUT2[2]));
  BUFX12 drc_bufs2530(.A (n_126), .Y (OUT2[0]));
  BUFX12 drc_bufs2531(.A (n_128), .Y (OUT1[0]));
  BUFX12 drc_bufs2532(.A (n_127), .Y (OUT2[1]));
  BUFX12 drc_bufs2533(.A (n_120), .Y (OUT2[7]));
  BUFX12 drc_bufs2534(.A (n_121), .Y (OUT1[3]));
  BUFX12 drc_bufs2535(.A (n_123), .Y (OUT1[6]));
  BUFX12 drc_bufs2536(.A (n_131), .Y (OUT1[1]));
  BUFX12 drc_bufs2537(.A (n_122), .Y (OUT1[4]));
  BUFX12 drc_bufs2538(.A (n_132), .Y (OUT1[5]));
  BUFX12 drc_bufs2539(.A (n_125), .Y (OUT1[2]));
  BUFX12 drc_bufs2540(.A (n_129), .Y (OUT1[7]));
  SDFFNSRX1 \reg6_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_9), .SI (reg6[2]), .Q (reg6[2]), .QN
       (UNCONNECTED96));
  SDFFNSRX1 \reg0_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_0), .SI (reg0[1]), .Q (reg0[1]), .QN
       (UNCONNECTED97));
  SDFFNSRX1 \reg1_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[3]), .SE (n_11), .SI (IN[3]), .Q (reg1[3]), .QN
       (UNCONNECTED98));
  SDFFNSRX1 \reg1_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[4]), .SE (n_11), .SI (IN[4]), .Q (reg1[4]), .QN
       (UNCONNECTED99));
  SDFFNSRX1 \reg5_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[2]), .SE (n_1), .SI (IN[2]), .Q (reg5[2]), .QN
       (UNCONNECTED100));
  SDFFNSRX1 \reg5_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[3]), .SE (n_1), .SI (IN[3]), .Q (reg5[3]), .QN
       (UNCONNECTED101));
  SDFFNSRX1 \reg5_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[4]), .SE (n_1), .SI (IN[4]), .Q (reg5[4]), .QN
       (UNCONNECTED102));
  SDFFNSRX1 \reg5_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[5]), .SE (n_1), .SI (IN[5]), .Q (reg5[5]), .QN
       (UNCONNECTED103));
  SDFFNSRX1 \reg1_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[5]), .SE (n_11), .SI (IN[5]), .Q (reg1[5]), .QN
       (UNCONNECTED104));
  SDFFNSRX1 \reg5_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[6]), .SE (n_1), .SI (IN[6]), .Q (reg5[6]), .QN
       (UNCONNECTED105));
  SDFFNSRX1 \reg5_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[7]), .SE (n_1), .SI (IN[7]), .Q (reg5[7]), .QN
       (UNCONNECTED106));
  SDFFNSRX1 \reg1_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[6]), .SE (n_11), .SI (IN[6]), .Q (reg1[6]), .QN
       (UNCONNECTED107));
  SDFFNSRX1 \reg6_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_9), .SI (reg6[0]), .Q (reg6[0]), .QN
       (UNCONNECTED108));
  SDFFNSRX1 \reg1_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[7]), .SE (n_11), .SI (IN[7]), .Q (reg1[7]), .QN
       (UNCONNECTED109));
  SDFFNSRX1 \reg2_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_13), .SI (reg2[0]), .Q (reg2[0]), .QN
       (UNCONNECTED110));
  SDFFNSRX1 \reg6_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_9), .SI (reg6[1]), .Q (reg6[1]), .QN
       (UNCONNECTED111));
  SDFFNSRX1 \reg0_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_0), .SI (reg0[0]), .Q (reg0[0]), .QN
       (UNCONNECTED112));
  SDFFNSRX1 \reg6_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_9), .SI (reg6[3]), .Q (reg6[3]), .QN
       (UNCONNECTED113));
  SDFFNSRX1 \reg6_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_9), .SI (reg6[4]), .Q (reg6[4]), .QN
       (UNCONNECTED114));
  SDFFNSRX1 \reg2_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_13), .SI (reg2[1]), .Q (reg2[1]), .QN
       (UNCONNECTED115));
  SDFFNSRX1 \reg6_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_9), .SI (reg6[5]), .Q (reg6[5]), .QN
       (UNCONNECTED116));
  SDFFNSRX1 \reg6_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_9), .SI (reg6[6]), .Q (reg6[6]), .QN
       (UNCONNECTED117));
  SDFFNSRX1 \reg2_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_13), .SI (reg2[2]), .Q (reg2[2]), .QN
       (UNCONNECTED118));
  SDFFNSRX1 \reg6_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_9), .SI (reg6[7]), .Q (reg6[7]), .QN
       (UNCONNECTED119));
  SDFFNSRX1 \reg7_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_10), .SI (reg7[0]), .Q (reg7[0]), .QN
       (UNCONNECTED120));
  SDFFNSRX1 \reg0_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_0), .SI (reg0[2]), .Q (reg0[2]), .QN
       (UNCONNECTED121));
  SDFFNSRX1 \reg2_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_13), .SI (reg2[3]), .Q (reg2[3]), .QN
       (UNCONNECTED122));
  SDFFNSRX1 \reg2_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_13), .SI (reg2[4]), .Q (reg2[4]), .QN
       (UNCONNECTED123));
  SDFFNSRX1 \reg7_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_10), .SI (reg7[1]), .Q (reg7[1]), .QN
       (UNCONNECTED124));
  SDFFNSRX1 \reg7_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_10), .SI (reg7[2]), .Q (reg7[2]), .QN
       (UNCONNECTED125));
  SDFFNSRX1 \reg7_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_10), .SI (reg7[3]), .Q (reg7[3]), .QN
       (UNCONNECTED126));
  SDFFNSRX1 \reg7_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_10), .SI (reg7[4]), .Q (reg7[4]), .QN
       (UNCONNECTED127));
  SDFFNSRX1 \reg0_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_0), .SI (reg0[6]), .Q (reg0[6]), .QN
       (UNCONNECTED128));
  SDFFNSRX1 \reg7_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_10), .SI (reg7[5]), .Q (reg7[5]), .QN
       (UNCONNECTED129));
  SDFFNSRX1 \reg7_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_10), .SI (reg7[6]), .Q (reg7[6]), .QN
       (UNCONNECTED130));
  SDFFNSRX1 \reg2_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_13), .SI (reg2[6]), .Q (reg2[6]), .QN
       (UNCONNECTED131));
  SDFFNSRX1 \reg7_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_10), .SI (reg7[7]), .Q (reg7[7]), .QN
       (UNCONNECTED132));
  SDFFNSRX1 \reg0_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_0), .SI (reg0[3]), .Q (reg0[3]), .QN
       (UNCONNECTED133));
  SDFFNSRX1 \reg2_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_13), .SI (reg2[7]), .Q (reg2[7]), .QN
       (UNCONNECTED134));
  SDFFNSRX1 \reg3_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[0]), .SE (n_8), .SI (reg3[0]), .Q (reg3[0]), .QN
       (UNCONNECTED135));
  SDFFNSRX1 \reg3_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[1]), .SE (n_8), .SI (reg3[1]), .Q (reg3[1]), .QN
       (UNCONNECTED136));
  SDFFNSRX1 \reg3_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[2]), .SE (n_8), .SI (reg3[2]), .Q (reg3[2]), .QN
       (UNCONNECTED137));
  SDFFNSRX1 \reg0_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_0), .SI (reg0[4]), .Q (reg0[4]), .QN
       (UNCONNECTED138));
  SDFFNSRX1 \reg0_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_0), .SI (reg0[5]), .Q (reg0[5]), .QN
       (UNCONNECTED139));
  SDFFNSRX1 \reg3_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[3]), .SE (n_8), .SI (reg3[3]), .Q (reg3[3]), .QN
       (UNCONNECTED140));
  SDFFNSRX1 \reg3_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[4]), .SE (n_8), .SI (reg3[4]), .Q (reg3[4]), .QN
       (UNCONNECTED141));
  SDFFNSRX1 \reg3_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_8), .SI (reg3[5]), .Q (reg3[5]), .QN
       (UNCONNECTED142));
  SDFFNSRX1 \reg3_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[6]), .SE (n_8), .SI (reg3[6]), .Q (reg3[6]), .QN
       (UNCONNECTED143));
  SDFFNSRX1 \reg2_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[5]), .SE (n_13), .SI (reg2[5]), .Q (reg2[5]), .QN
       (UNCONNECTED144));
  SDFFNSRX1 \reg3_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_8), .SI (reg3[7]), .Q (reg3[7]), .QN
       (UNCONNECTED145));
  SDFFNSRX1 \reg0_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (IN[7]), .SE (n_0), .SI (reg0[7]), .Q (reg0[7]), .QN
       (UNCONNECTED146));
  SDFFNSRX1 \reg4_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[0]), .SE (n_12), .SI (IN[0]), .Q (reg4[0]), .QN
       (UNCONNECTED147));
  SDFFNSRX1 \reg4_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[1]), .SE (n_12), .SI (IN[1]), .Q (reg4[1]), .QN
       (UNCONNECTED148));
  SDFFNSRX1 \reg1_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[0]), .SE (n_11), .SI (IN[0]), .Q (reg1[0]), .QN
       (UNCONNECTED149));
  SDFFNSRX1 \reg4_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[2]), .SE (n_12), .SI (IN[2]), .Q (reg4[2]), .QN
       (UNCONNECTED150));
  SDFFNSRX1 \reg4_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[3]), .SE (n_12), .SI (IN[3]), .Q (reg4[3]), .QN
       (UNCONNECTED151));
  SDFFNSRX1 \reg4_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[4]), .SE (n_12), .SI (IN[4]), .Q (reg4[4]), .QN
       (UNCONNECTED152));
  SDFFNSRX1 \reg4_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[5]), .SE (n_12), .SI (IN[5]), .Q (reg4[5]), .QN
       (UNCONNECTED153));
  SDFFNSRX1 \reg1_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[1]), .SE (n_11), .SI (IN[1]), .Q (reg1[1]), .QN
       (UNCONNECTED154));
  SDFFNSRX1 \reg4_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[6]), .SE (n_12), .SI (IN[6]), .Q (reg4[6]), .QN
       (UNCONNECTED155));
  SDFFNSRX1 \reg4_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg4[7]), .SE (n_12), .SI (IN[7]), .Q (reg4[7]), .QN
       (UNCONNECTED156));
  SDFFNSRX1 \reg1_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg1[2]), .SE (n_11), .SI (IN[2]), .Q (reg1[2]), .QN
       (UNCONNECTED157));
  SDFFNSRX1 \reg5_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[0]), .SE (n_1), .SI (IN[0]), .Q (reg5[0]), .QN
       (UNCONNECTED158));
  SDFFNSRX1 \reg5_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (clk), .D
       (reg5[1]), .SE (n_1), .SI (IN[1]), .Q (reg5[1]), .QN
       (UNCONNECTED159));
  NAND2X2 g685(.A (INaddr[1]), .B (n_5), .Y (n_13));
  AND2X1 g686(.A (n_3), .B (n_7), .Y (n_12));
  AND2X1 g688(.A (n_3), .B (n_4), .Y (n_11));
  OR2X1 g689(.A (n_3), .B (n_6), .Y (n_10));
  NAND2X2 g690(.A (INaddr[1]), .B (n_7), .Y (n_9));
  NAND2X2 g692(.A (INaddr[1]), .B (n_4), .Y (n_8));
  NOR2BX1 g694(.AN (INaddr[2]), .B (INaddr[0]), .Y (n_7));
  NAND2X1 g695(.A (INaddr[0]), .B (INaddr[2]), .Y (n_6));
  NOR2XL g697(.A (INaddr[0]), .B (INaddr[2]), .Y (n_5));
  NOR2BX1 g698(.AN (INaddr[0]), .B (INaddr[2]), .Y (n_4));
  INVX1 g699(.A (INaddr[1]), .Y (n_3));
  NOR2BX2 g2(.AN (n_3), .B (n_6), .Y (n_1));
  NAND2BX2 g700(.AN (INaddr[1]), .B (n_5), .Y (n_0));
endmodule

module proccessor(result, OUT1, OUT2, Data2, mux1out, immediate,
     mux2out, Select, clk, reset);
  input clk, reset;
  output [7:0] result, OUT1, OUT2, Data2, mux1out, immediate, mux2out;
  output [2:0] Select;
  wire clk, reset;
  wire [7:0] result, OUT1, OUT2, Data2, mux1out, immediate, mux2out;
  wire [2:0] Select;
  wire [2:0] OUT2addr;
  wire [2:0] Read_addr;
  wire [31:0] instruction;
  wire [2:0] INaddr;
  wire [2:0] OUT1addr;
  wire UNCONNECTED160, UNCONNECTED161, UNCONNECTED162, UNCONNECTED163,
       UNCONNECTED164, UNCONNECTED165, UNCONNECTED166, UNCONNECTED167;
  wire UNCONNECTED168, UNCONNECTED169, UNCONNECTED170, UNCONNECTED171,
       UNCONNECTED172, UNCONNECTED173, UNCONNECTED174, UNCONNECTED175;
  wire UNCONNECTED176, UNCONNECTED177, UNCONNECTED178, UNCONNECTED179,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5,
       UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z8,
       UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10;
  wire UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z18;
  wire UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z22, comp_signal,
       imm_signal, n_68, n_78;
  wire n_88, n_98, n_108, n_118, n_128, n_138, n_148, n_157;
  mux mux1(mux1out, comp_signal, Data2, OUT2);
  mux_29 mux2(mux2out, imm_signal, {immediate[7:3], OUT2addr[2],
       immediate[1:0]}, mux1out);
  alu myalu(result, mux2out, OUT1, {Select[2:1], n_157});
  compliment mycomp(Data2, OUT2);
  counter mycounter(Read_addr, clk, reset);
  CU mycu({UNCONNECTED162, UNCONNECTED161, UNCONNECTED160},
       {UNCONNECTED165, UNCONNECTED164, UNCONNECTED163},
       {UNCONNECTED168, UNCONNECTED167, UNCONNECTED166},
       {UNCONNECTED176, UNCONNECTED175, UNCONNECTED174, UNCONNECTED173,
       UNCONNECTED172, UNCONNECTED171, UNCONNECTED170, UNCONNECTED169},
       {UNCONNECTED179, UNCONNECTED178, UNCONNECTED177}, imm_signal,
       comp_signal, {instruction[31:27], Select, UNCONNECTED_HIER_Z22,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z18,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z6,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z});
  regInstructions myreg({instruction[31:27], Select,
       instruction[23:19], INaddr, instruction[15:11], OUT1addr,
       immediate[7:3], OUT2addr[2], immediate[1:0]}, clk, Read_addr);
  regfile8x8a myregister(OUT1, OUT2, clk, INaddr, OUT1addr,
       {OUT2addr[2], immediate[1:0]}, {n_98, n_148, n_128, n_78, n_118,
       n_108, n_138, n_88});
  regfile8x8a_33 myregister1(OUT1, OUT2, clk, INaddr, {OUT1addr[2],
       n_68, OUT1addr[0]}, immediate[2:0], result);
  BUFX12 drc_buf_sp7(.A (OUT2addr[2]), .Y (immediate[2]));
  BUFX8 drc_buf_sp16(.A (OUT1addr[1]), .Y (n_68));
  BUFX2 drc_buf_sp25(.A (result[4]), .Y (n_78));
  BUFX2 drc_buf_sp34(.A (result[0]), .Y (n_88));
  BUFX2 drc_buf_sp43(.A (result[7]), .Y (n_98));
  BUFX2 drc_buf_sp52(.A (result[2]), .Y (n_108));
  BUFX2 drc_buf_sp61(.A (result[3]), .Y (n_118));
  BUFX2 drc_buf_sp70(.A (result[5]), .Y (n_128));
  BUFX2 drc_buf_sp79(.A (result[1]), .Y (n_138));
  BUFX2 drc_buf_sp88(.A (result[6]), .Y (n_148));
  BUFX2 drc_buf_sp96(.A (Select[0]), .Y (n_157));
endmodule

